// Copyright 2017, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'profile_fonts.dart';

const todoLineHeight = 63.0;
const appBarHeight = 63.0;
const appBarExpandedHeight = 212.0;
const appBarMinFontSize = 27.8;
const appBarMaxFontSize = 40.0;
const doneStyle = const TextStyle(
  color: TodoColors.done,
  decoration: TextDecoration.lineThrough,
);
const kShrinePink50 = const Color(0xFFFEEAE6);
const kShrinePink100 = const Color(0xFFFEDBD0);
const kShrinePink300 = const Color(0xFFFBB8AC);

const kShrineBrown900 = const Color(0xFF442B2D);

const kShrineErrorRed = const Color(0xFFC5032B);

const kShrineSurfaceWhite = const Color(0xFFFFFBFA);
const kShrineBackgroundWhite = Colors.white;

class TodoColors {
  static const Color primaryDark = const Color(0xFF863352);
  static const Color primary = const Color(0xFFB43F54);
  static const Color primaryLight = const Color(0xFFCA4855);
  static const Color background = const Color(0xFF1C1E27);
  static const Color done = const Color(0xFFBABCBE);
  static const Color accent = const Color(0xFF42B2CC);
  static const Color disabled = const Color(0xFFBABCBE);
  static const Color line = const Color(0xFF414044);

  static final textStyle = new TextStyle(
      color: accent,
      fontWeight: FontWeight.w700,
      fontSize: 18.0,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle2 = new TextStyle(
      color: background,
      fontWeight: FontWeight.w500,
      fontSize: 16.0,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle3 = new TextStyle(
      color: primary,
      fontWeight: FontWeight.w900,
      fontSize: 16.0,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle4 = new TextStyle(
      color: accent,
      fontWeight: FontWeight.w900,
      fontSize: 13.0,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle5 = new TextStyle(
      fontWeight: FontWeight.w900,
      fontSize: 20.0,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle6 = new TextStyle(
      fontWeight: FontWeight.w700,
      fontSize: 25.0,
      color: Colors.black,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle7 = new TextStyle(
      fontWeight: FontWeight.w700,
      fontSize: 20.0,
      color: Colors.black,
      fontFamily: ProfileFontNames.TimeBurner);

  static final textStyle8 = new TextStyle(
      fontWeight: FontWeight.w700,
      fontSize: 10.0,
      color: Colors.black,
      fontFamily: ProfileFontNames.TimeBurner);
  Color c = Colors.amber;
  static const baseColors = <ColorSwatch>[
    //Profile
    ColorSwatch(0xFF6AB7A8, {
      'highlight': Color(0xFF6AB7A8),
      'splash': Color(0xFF0ABC9B),
    }),
    //Projects
    ColorSwatch(0xFF8899A8, {
      'highlight': Color(0xFF8899A8),
      'splash': Color(0xFFA9CAE8),
    }),
    //Pending Requests
    ColorSwatch(0xFF81A56F, {
      'highlight': Color(0xFF81A56F),
      'splash': Color(0xFF7CC159),
    }),

    //Weeks Availability
    ColorSwatch(0xFFFFC7DE, {
      'highlight': Color(0xFFFFB7DE),
      'splash': Color(0xFFF94CBF),
    }),
  ];

  static const icons = <String>[
    'assets/icons/length.png',
    'assets/icons/area.png',
    'assets/icons/volume.png',
    'assets/icons/availability.png',
    'assets/icons/power.png',
    'assets/icons/digital_storage.png',
  ];

  static const baseColors2 = <ColorSwatch>[
    //Profile
    ColorSwatch(0xFF6AB7A8, {
      'highlight': Color(0xFF6AB7A8),
      'splash': Color(0xFF0ABC9B),
    }),
    //Projects
    ColorSwatch(0xFFFFBF00,  {
      'highlight': Color(0xFFFFD28E),
      'splash': Color(0xFFFFA41C),
    }),
    //Pending Requests
    ColorSwatch(0xFFFFC7DE, {
      'highlight': Color(0xFFFFB7DE),
      'splash': Color(0xFFF94CBF),
    }),
    //Started Projects
    ColorSwatch(0xFF8899A8, {
      'highlight': Color(0xFF8899A8),
      'splash': Color(0xFFA9CAE8),
    }),
    //Upcoming Projects
    ColorSwatch(0xFFEAD37E, {
      'highlight': Color(0xFFEAD37E),
      'splash': Color(0xFFFFE070),
    }),
    //Explore Users
    ColorSwatch(0xFF81A56F, {
      'highlight': Color(0xFF81A56F),
      'splash': Color(0xFF7CC159),
    }),
    //Explore Devices
    ColorSwatch(0xFFD7C0E2, {
      'highlight': Color(0xFFD7C0E2),
      'splash': Color(0xFFCA90E5),
    }),
    //Closed Projects
    ColorSwatch(0xFFCE9A9A, {
      'highlight': Color(0xFFCE9A9A),
      'splash': Color(0xFFF94D56),
      'error': Color(0xFF912D2D),
    }),
    //Weeks Availability
    ColorSwatch(0xFF779A9A, {
      'highlight': Color(0xFF3366FF),
      'splash': Color(0xFF3366FF),
      'error': Color(0xFF3366FF),
    }),
  ];

  static const List<String> all_emails = [
    'josee.uwayezu@Enumerator.com',
    'innocent.mushamuka@Enumerator.com',
    'diane.ingabirehirwa@Enumerator.com',
    'esperance.uwitonze@Enumerator.com',
    'nadege.umurutasate@Transcriber.com',
    'eric.karama@Enumerator.com',
    'flavia.kantengwa@Field-Coordinator.com',
    'olivier.pacifiqueniyomugabo@Enumerator.com',
    'blaise.musabe@Enumerator.com',
    'aloysie.niyoyita@Enumerator.com',
    'juliet.nyirasafari@Enumerator.com',
    'protais.nkundineza@Enumerator.com',
    'bernard.uwayisaba@Field-Coordinator.com',
    'evariste.nizeyimana@Enumerator.com',
    'bernard.nkurunziza@Enumerator.com',
    'clarisse.mukundwa@Translator.com',
    'olivier.mutabazi@Enumerator.com',
    'charles.mwizerwa@Enumerator.com',
    'claire.akamanzikaneza@Enumerator.com',
    'carine.kalinda@Enumerator.com',
    'jean.dedieuuwihaye@Enumerator.com',
    'blandine.umuziranenge@Enumerator.com',
    'geoffrey.mugisha@Enumerator.com',
    'sonia.hirwa@Enumerator.com',
    'annick.izabayo@Enumerator.com',
    'ariane.merciisimbi@Enumerator.com',
    'egide.sakindi@Enumerator.com',
    'florence.sumwiza@Enumerator.com',
    'hyacinthe.kakuze@Enumerator.com',
    'redempta.ingabire@Field-Supervisor.com',
    'joseph.uwimana@Enumerator.com',
    'vital.habimana@Enumerator.com',
    'pie.nkubito@Enumerator.com',
    'denis.karenzi@Enumerator.com',
    'jean.boscohakizimana@Enumerator.com',
    'angelo.igitego@Translator.com',
    'denise.murinzi@Enumerator.com',
    'francine.irankunda@Enumerator.com',
    'francoise.uwineza@Enumerator.com',
    'betty.nyirahabimana@Enumerator.com',
    'joyce.rulinda@Enumerator.com',
    'francois.imanayumvabayo@Enumerator.com',
    'chantal.kabatesi@Enumerator.com',
    'yvette.uwamariya@Enumerator.com',
    'afrika.prudencehabinshuti@Enumerator.com',
    'clementine.mukagatare@Enumerator.com',
    'claude.mudahemuka@Enumerator.com',
    'yvette.amahoro@Field-Coordinator.com',
    'gustave.niringire@Enumerator.com',
    'francoise.uwiringiyingabire@Enumerator.com',
    'jean.paulniyibizi@Enumerator.com',
    'fabienne.mutamuriza@Enumerator.com',
    'angelique.kwizera@Enumerator.com',
    'pauline.kimenyi@Enumerator.com',
    'kellia.umulisa@Enumerator.com',
    'alice.nibakure@Enumerator.com',
    'bertrand.rutagarama@Translator.com',
    'alexis.gisore@Enumerator.com',
    'leontine.byukusenge@Enumerator.com',
    'jackson.ngiruwonsanga@Enumerator.com',
    'olivier.mutijimana@Enumerator.com',
    'anitha.uwasesendakize@Enumerator.com',
    'pascal.habineza@Translator.com',
    'jean.claudendayiragije@Enumerator.com',
    'amandine.karire@Enumerator.com',
    'scholas.buranga@Enumerator.com',
    'alliyah.kaneza@Enumerator.com',
    'abdou.kamanzi@Enumerator.com',
    'clemence.tuyishimire@Enumerator.com',
    'honoree.victoiremukashema@Enumerator.com',
    'alice.nibagirwe@Enumerator.com',
    'henry.markrugaba@Enumerator.com',
    'marie.aimeeuwera@Enumerator.com',
    'hyacinthe.mushimiyimana@Enumerator.com',
    'ingabire.dianehirwa@Enumerator.com',
    'francois.regisniringiyimana@Enumerator.com',
    'alice.neza@Enumerator.com',
    'sharon.uwineza@Enumerator.com',
    'gloriose.ingabire@Field-Coordinator.com',
    'sonia.umutoniwase@Enumerator.com',
    'susan.teta@Translator.com',
    'norah.natukunda@Enumerator.com',
    'ben.dedalesixtehigiro@Enumerator.com',
    'emmanuel.twagirayezu@Enumerator.com',
    'evariste.nyirimanzi@Enumerator.com',
    'clarisse.uwase@Enumerator.com',
    'jean.paulhabimana@Enumerator.com',
    'christian.shema@Enumerator.com',
    'angelique.ingabire@Enumerator.com',
    'bernice.iradukunda@Enumerator.com',
    'flora.umulisa@Enumerator.com',
    'etienne.babuzindunduro@Enumerator.com',
    'leatitia.mukeshimana@Enumerator.com',
    'anicet.nsengumuremyi@Enumerator.com',
    'evelyne.mutuyimana@Enumerator.com',
    'octave.vuguziga@Enumerator.com',
    'liliose.umutesi@Enumerator.com',
    'clarisse.impano@Enumerator.com',
    'eric.rurinda@Enumerator.com',
    'alice.uwera@Translator.com',
    'toute.chantalumwiza@Enumerator.com',
    'narcisse.mutanguha@Enumerator.com',
    'tharcisse.bizimana@Enumerator.com',
    'godfrey.mutsinzi@Enumerator.com',
    'eric.gasana@Enumerator.com',
    'emmanuel.twagirimana@Enumerator.com',
    'magalie.ntahokaja@Translator.com',
    'donatien.majyambere@Enumerator.com',
    'emmanuel.brunondayisenga@Enumerator.com',
    'marie.auroreniyitangamanzi@Transcriber.com',
    'solange.uwingeri@Enumerator.com',
    'divine.nikuze@Field-Coordinator.com',
    'adrien.gakumbahabimana@Enumerator.com',
    'rhona.tumushabe@Enumerator.com',
    'diane.ishimwe@Enumerator.com',
    'benjamin.cyuzuzo@Enumerator.com',
    'geraldine.mukantabana@Enumerator.com',
    'christelle.uwimana@Enumerator.com',
    'shakila.umutonikamatali@Translator.com',
    'jean.baptisteiradukunda@Enumerator.com',
    'jean.ntawanguwe@Transcriber.com',
    'emmy.kangwege@Enumerator.com',
    'gaspard.nzasabimfura@Transcriber.com',
    'rachel.cyuzuzo@Transcriber.com',
    'lucie.dusengiyaremye@Field-Supervisor.com',
    'anita.mamenero@Enumerator.com',
    'philbert.muhire@Enumerator.com',
    'billy.gilberthabimanacyusa@Translator.com',
    'david.ndayisenga@Enumerator.com',
    'dorcyne.nishimwe@Enumerator.com',
    'barbara.umuhoza@Translator.com',
    'josiane.nishimwe@Enumerator.com',
    'fortunee.umuhozawase@Enumerator.com',
    'ntegana.musirimu@Enumerator.com',
    'aline.mukakayumba@Enumerator.com',
    'patrice.nshuti@Enumerator.com',
    'deogratias.nshimiyimana@Enumerator.com',
    'violet.kagabirwa@Enumerator.com',
    'nshuti.samantha@Enumerator.com',
    'dorothee.karehe@Enumerator.com',
    'marie.claudineumubyeyi@Enumerator.com',
    'jeannette.mireilleiradukunda@Enumerator.com',
    'jimmy.ruhanga@Enumerator.com',
    'leonille.mutambarungu@Enumerator.com',
    'camarade.samuelamerika@Enumerator.com',
    'charlene.kanyange@Enumerator.com',
    'herve.nyirimihigo@Enumerator.com',
    'emma.roseuwimana@Enumerator.com',
    'pacifique.kwizera@Enumerator.com',
    'immaculee.nyirandizihiwe@Enumerator.com',
    'nadine.tuyishime@Enumerator.com',
    'valentine.mutamulizambayiha@Enumerator.com',
    'theophile.nyirimana@Enumerator.com',
    'elie.mandela@Translator.com',
    'rosine.nishimwe@Enumerator.com',
    'assuman.muhire@Enumerator.com',
    'fidele.maniraguha@Enumerator.com',
    'nadine.jessicaumuhoza@Enumerator.com',
    'leon.habineza@Enumerator.com',
    'sophie.akimana@Enumerator.com',
    'clemence.nduwayo@Enumerator.com',
    'juliet.tusingirwe@Enumerator.com',
    'morris.kayitare@Translator.com',
    'jean.claudeturatsinze@Enumerator.com',
    'marcel.hagenashema@Enumerator.com',
    'anitha.uwingabiye@Enumerator.com',
    'marie.chantalmukantwali@Enumerator.com',
    'patrick.tuyisenge@Enumerator.com',
    'angelique.muhawenimana@Enumerator.com',
    'anne.niyomubyeyi@Enumerator.com',
    'mireille.umutonisekamana@Transcriber.com',
    'grace.uwase@Translator.com',
    'consolee.bagwaneza@Enumerator.com',
    'noel.ndamukunda@Enumerator.com',
    'manasse.twagiramungu@Field-Coordinator.com',
    'emeline.hategekimana@Field-Coordinator.com',
    'yvette.umugiraneza@Enumerator.com',
    'dieudonne.tuyisabyimbabazi@Enumerator.com',
    'therese.uwamahoro@Translator.com',
    'patient.nshongore@Enumerator.com',
    'christian.kayonga@Enumerator.com',
    'denise.kayitesingamije@Enumerator.com',
    'xavier.nyandwi@Enumerator.com',
    'martin.hubertikuramutse@Enumerator.com',
    'jean.claudenshimiyimana@Enumerator.com',
    'jean.bosconsengiyumva@Enumerator.com',
    'elisee.dushimimana@Enumerator.com',
    'john.nshaija@Enumerator.com',
    'christian.muhire@Enumerator.com',
    'jacqueline.bamurange@Enumerator.com',
    'vanessa.ingabire@Enumerator.com',
    'petrine.muhoza@Enumerator.com',
    'james.nkuranga@Enumerator.com',
    'eric.ntakirutimana@Enumerator.com',
    'christophe.rukundo@Enumerator.com',
    'clarisse.kazayirwa@Enumerator.com',
    'fabiola.bagorora@Enumerator.com',
    'christine.nyirandikumana@Enumerator.com',
    'sixbert.shema@Enumerator.com',
    'marie.assoumptaumuhoza@Enumerator.com',
    'christian.nkubito@Enumerator.com',
    'jean.baptistenyaminani@Enumerator.com',
    'pie.celestinhakizimana@Enumerator.com',
    'rebecca.tuganeyesu@Enumerator.com',
    'sylvia.ingabire@Enumerator.com',
    'grace.nyiramatungo@Enumerator.com',
    'grace.umuganwa@Enumerator.com',
    'charles.hitimana@Enumerator.com',
    'hamdoun.twagirimana@Enumerator.com',
    'joyce.munezero@Field-Coordinator.com',
    'theobald.nshimiyimana@Enumerator.com',
    'theodomir.ntasoni@Enumerator.com',
    'rodrigue.bukozi@Enumerator.com',
    'irene.nteziryayo@Enumerator.com',
    'anne.mukarebero@Enumerator.com',
    'egidie.nirere@Enumerator.com',
    'solange.dusabiyera@Enumerator.com',
    'sandrine.uwiduhaye@Enumerator.com',
    'jean.paulishimwe@Enumerator.com',
    'joseph.murinzi@Enumerator.com',
    'yvette.umwali@Enumerator.com',
    'florence.niyigena@Enumerator.com',
    'salwa.uwabasindi@Enumerator.com',
    'betty.mukankusi@Enumerator.com',
    'emylie.gahimbare@Enumerator.com',
    'samantha.mugabe@Enumerator.com',
    'stella.mukakalisa@Enumerator.com',
    'gloria.igiraneza@Enumerator.com',
    'rosalie.mukeshimana@Enumerator.com',
    'tresor.kambanda@Translator.com',
    'faith.mutesi@Enumerator.com',
    'sandrine.uwamahoro@Enumerator.com',
    'alice.benihirwe@Enumerator.com',
    'thamar.gatesi@Enumerator.com',
    'rosine.uwamariya@Enumerator.com',
    'valentine.nishimwe@Enumerator.com',
    'geoffrey.karara@Enumerator.com',
    'sonia.angerugwiro@Transcriber.com',
    'clarisse.mukandindacyuzuzo@Enumerator.com',
    'euphrosine.mukankebukande@Enumerator.com',
    'aloys.ishimwe@Enumerator.com',
    'emmanuel.musanganya@Enumerator.com',
    'orly.mugwaneza@Enumerator.com',
    'irma.girimbabazi@Enumerator.com',
    'joseph.elvinkatete@Enumerator.com',
    'jessica.irambona@Enumerator.com',
    'jeanine.nyiramana@Enumerator.com',
    'yvette.abijuru@Transcriber.com',
    'fred.kaberuka@Enumerator.com',
    'joseph.nsengimana@Enumerator.com',
    'jonas.niyogakiza@Enumerator.com',
    'patricia.ingabire@Enumerator.com',
    'etienne.musemakweli@Field-Coordinator.com',
    'claudien.rudasingwa@Enumerator.com',
    'pauline.kezakimana@Enumerator.com',
    'octave.gakunzi@Enumerator.com',
    'peter.muvunyi@Enumerator.com',
    'yves.fabienkarasira@Enumerator.com',
    'olivier.duhoranimana@Enumerator.com',
    'vedaste.nizeyimana@Enumerator.com',
    'private.dukundimana@Enumerator.com',
    'sylvie.karemera@Enumerator.com',
    'raissa.mugisha@Translator.com',
    'muhodari.kadugano@Enumerator.com',
    'fraterne.mutimanama@Enumerator.com',
    'perpetue.dusabimana@Enumerator.com',
    'raissa.kamaliza@Translator.com',
    'rosine.uwantege@Field-Coordinator.com',
    'arlette.saroniyibizi@Enumerator.com',
    'daniella.ujeneza@Translator.com',
    'albin.shema@Enumerator.com',
    'thomas.byiringiro@Enumerator.com',
    'sam.kagwisagye@Enumerator.com',
    'christian.rwabununga@Enumerator.com',
    'elias.kagabo@Transcriber.com',
    'didier.usanase@Enumerator.com',
    'clarisse.gahunzireuwitonze@Enumerator.com',
    'olive.tuyishimire@Transcriber.com',
    'lyvine.umutoni@Enumerator.com',
    'noel.olivieringabire@Enumerator.com',
    'eric.kirezi@Field-Supervisor.com',
    'liliose.mukeshimana@Enumerator.com',
    'gisele.mwizerwa@Enumerator.com',
    'joseph.manzi@Enumerator.com',
    'constantin.bihoyiki@Enumerator.com',
    'dominique.ntwari@Enumerator.com',
    'jackline.mugoboka@Enumerator.com',
    'jean.felixkayiranga@Enumerator.com',
    'philbert.ishimwe@Enumerator.com',
    'celine.mukantwali@Enumerator.com',
    'jean.dedieudushimimana@Enumerator.com',
    'bernard.nshimiyimana@Enumerator.com',
    'delphine.abijuru@Enumerator.com',
    'marie.aimeenakure@Enumerator.com',
    'assumpta.cyuzuzo@Enumerator.com',
    'jean.baptistekwizera@Translator.com',
    'diane.karire@Enumerator.com',
    'beatrice.safikalumbi@Enumerator.com',
    'aphrodis.nshizirungu@Enumerator.com',
    'jean.dedieuntivuguruzwa@Enumerator.com',
    'magnifique.mukundwa@Transcriber.com',
    'moise.bonheur@Enumerator.com',
    'marius.munezero@Enumerator.com',
    'julius.ntaganda@Enumerator.com',
    'juliet.elisagiraso@Translator.com',
    'agnes.muhawenimana@Enumerator.com',
    'aline.kenzangirankugire@Enumerator.com',
    'belinda.ingabire@Field-Coordinator.com',
    'clement.rugira@Enumerator.com',
    'diane.clarisseuwibambe@Enumerator.com',
    'sarah.uwineza@Enumerator.com',
    'honoré.ndayishimye@Enumerator.com',
    'dativa.kabatsi@Enumerator.com',
    'jean.paulrugwiro@Enumerator.com',
    'honorine.uwera@Enumerator.com',
    'denys.buhake@Enumerator.com',
    'sarah.kamikazi@Enumerator.com',
    'clementine.nyirarukundo@Enumerator.com',
    'janecie.rangiraumutoni@Enumerator.com',
    'serge.priamnsanzineza@Transcriber.com',
    'appolinaire.twagiramungu@Enumerator.com',
    'serapie.hakizimana@Enumerator.com',
    'fabrice.birasa@Enumerator.com',
    'vestine.masengesho@Enumerator.com',
    'steven.mucyo@Translator.com',
    'diane.mukabagorora@Enumerator.com',
    'fred.mukunzi@Enumerator.com',
    'ally.mugabukenukwe@Enumerator.com',
    'esther.nsimirelulando@Field-Supervisor.com',
    'donatha.mugirase@Translator.com',
    'philomene.nyirarukundo@Enumerator.com',
    'clarisse.kamanziakagera@Translator.com',
    'jeannette.batamuliza@Enumerator.com',
    'felicien.irafasha@Enumerator.com',
    'janvier.bananezakayitare@Qualitative.com',
    'cedric.kigenzamugabo@Translator.com',
    'answar.twizerimana@Enumerator.com',
    'ines.michelleiradukunda@Enumerator.com',
    'jean.francoisnyamuniga@Enumerator.com',
    'rene.francissimbimvuyekure@Transcriber.com',
    'adeline.tuyizeregasinzigwa@Enumerator.com',
    'grace.dusabe@Enumerator.com',
    'jean.dedieudusenge@Enumerator.com',
    'charlotte.uwimana@Transcriber.com',
    'emma.roseumwali@Field-Coordinator.com',
    'billy.michelmigambi@Enumerator.com',
    'damien.munyandekwe@Enumerator.com',
    'marie.louiseniragire@Enumerator.com',
    'francoise.uwanyirigira@Enumerator.com',
    'marie.clairegihozo@Enumerator.com',
    'benjamin.abijuru@Enumerator.com',
    'francine.uwamahoro@Enumerator.com',
    'samson.gatera@Enumerator.com',
    'diana.umutoniburamba@Enumerator.com',
    'joel.shumbusho@Enumerator.com',
    'alphonsine.uwantege@Enumerator.com',
    'jean.damascenetuyizere@Enumerator.com',
    'brenda.mutoni@Enumerator.com',
    'yvette.nyinawamuntu@Enumerator.com',
    'quintia.iradukunda@Translator.com',
    'cansilde.ingabire@Enumerator.com',
    'michel.ndayishimiye@Enumerator.com',
    'marie.gracemuhimpundu@Enumerator.com',
    'josiane.mukayitesi@Enumerator.com',
    'nicole.beza@Enumerator.com',
    'aimable.nsengiyumva@Enumerator.com',
    'jean.damascenentakirutimana@Enumerator.com',
    'frank.karengera@Enumerator.com',
    'jean.ericcyizamugabe@Enumerator.com',
    'audace.nakeshimana@Translator.com',
    'allen.ingabire@Translator.com',
    'agnes.bamurange@Translator.com',
    'aisha.umutesi@Enumerator.com',
    'lucie.tuyishime@Enumerator.com',
    'elisabeth.yambabariye@Enumerator.com',
    'dina.marcellaabeneto@Enumerator.com',
    'hassan.karekezi@Enumerator.com',
    'herve.rurangwairadukunda@Translator.com',
    'lambert.habimana@Enumerator.com',
    'desire.ngurusu@Enumerator.com',
    'aime.laurenttwizerimana@Translator.com',
    'felix.mucyo@Enumerator.com',
    'simplice.ihirwe@Enumerator.com',
    'justine.mucyo@Enumerator.com',
    'jeanne.francoisemukabarezi@Enumerator.com',
    'jean.dedieuuwayezu@Enumerator.com',
    'perfect.mfashijwenimana@Transcriber.com',
    'emmanuel.uwayezu@Enumerator.com',
    'patrick.ndayambaje@Field-Coordinator.com',
    'richard.ngirumuremyi@Enumerator.com',
    'didier.girumuturanyi@Enumerator.com',
    'blandine.nirere@Enumerator.com',
    'jeanne.uwimana@Enumerator.com',
    'norbert.kwizera@Enumerator.com',
    'sabin.sheja@Enumerator.com',
    'aime.bienfaitigiraneza@Translator.com',
    'pascaline.mugiranezamunezero@Transcriber.com',
    'thierry.ndezemaniragaba@Enumerator.com',
    'ruth.fionabayimenye@Enumerator.com',
    'theodosie.uwitonze@Enumerator.com',
    'richard.basanase@Enumerator.com',
    'micheline.kwizera@Enumerator.com',
    'claudette.igiraneza@Transcriber.com',
    'theophile.kalisa@Enumerator.com',
    'silas.gasasira@Enumerator.com',
    'josiane.uwamahoro@Enumerator.com',
    'laetitia.uwera@Field-Coordinator.com',
    'marie.rosemuhoza@Enumerator.com',
    'aulique.bereniceiguhozesindikubwabo@Enumerator.com',
    'christian.ndaruhuye@Enumerator.com',
    'elithe.redemptainara@Enumerator.com',
    'obed.nahayo@Field-Supervisor.com',
    'blandine.uwera@Enumerator.com',
    'eric.ntaganira@Enumerator.com',
    'alain.christianruzindana@Enumerator.com',
    'albert.dukuzumuremyi@Enumerator.com',
    'alain.mwizerwa@Enumerator.com',
    'ross.erickarambizi@Enumerator.com',
    'emerance.iragena@Enumerator.com',
    'malik.martialmanziruzindaza@Enumerator.com',
    'odette.nishimwe@Enumerator.com',
    'didier.gashema@Enumerator.com',
    'aline.uwineza@Enumerator.com',
    'ange.sybillesingiza@Enumerator.com',
    'norette.ingabire@Translator.com',
    'pamela.rudahunga@Transcriber.com',
    'pamela.marieclaudemizero@Enumerator.com',
    'gaudence.ndayambaje@Enumerator.com',
    'marie.nellyadelineuwayezu@Field-Supervisor.com',
    'alice.mukeshimana@Enumerator.com',
    'erick.joseph@Enumerator.com',
  ];
  static const List<List<String>> names = [
    ['Xbvn7UtlLlfNj4Z37bFtgEH1VJm2','christian', 'nkubito'],
    ['pkL45yLpIEeqr4ngbmKX0ff9DdO2','toute', 'chantalumwiza'],
    ['JyMixoU1ILXf0kacGHQimTza2F32','octave', 'vuguziga'],
    ['UqqnztoKCYYTbo3z1t9dkmB0yoS2','denis', 'karenzi'],
    ['odqbJSZkbtZplCW1c4xdKxuopzR2','evariste', 'nyirimanzi'],
    ['mECztum2IxeMnE5ZgiFAWF8HXG93','juliet', 'tusingirwe'],
    ['4nc1O4Fk6WY9tonPAtjCwXq9xzx2','fortunee', 'umuhozawase'],
    ['blCWLCfD5TNHLjk1Io7VD3aHx9A2','claudien', 'rudasingwa'],
    ['p8uFPSOEY0QYh6zvGiJgbWGRIrh2','alice', 'nibagirwe'],
    ['Zgb7m9R388c6fABHZ27B9May11B3','albert', 'dukuzumuremyi'],
    ['Z4mY36u1WWUXHhUWc5QxjCoYrWy1','immaculee', 'nyirandizihiwe'],
    ['g7DFyTqvS6VmF60KUvlexc0yLh12','sonia', 'angerugwiro'],
    ['P57tr4fThcWf1wWsDlBB6iunXnl1','philbert', 'muhire'],
    ['Ihy026q0pmWXY1ecqdiJB6YxbvD2','dominique', 'ntwari'],
    ['Yl8icoVEIcSDduyLYG6lWaP49M92','marcel', 'hagenashema'],
    ['KJzeDxdWyaSkI9DcGevKv1HJbBT2','clarisse', 'mukandindacyuzuzo'],
    ['lFZKHfw7rKcm9fGtsrLh6pk06Bv1','charles', 'hitimana'],
    ['SrLAQvOGSvWxq9xXtAheFjKe5fL2','christian', 'shema'],
    ['9PM2QQ1TL6TtbjqIc1fRj18gtzF3','aloys', 'ishimwe'],
    ['vllUxLoXlZSuHedpMXxf3RxB0tu2','yvette', 'uwamariya'],
    ['RCm5scnJ5TT8EAO3mmuWfIT4xSa2','clementine', 'mukagatare'],
    ['KEk0uYxLOGhPgtAf7noPYVwhX6C2','jean', 'felixkayiranga'],
    ['eFtEOfONiUe1bMsYHZisl3IllTM2','theodomir', 'ntasoni'],
    ['SvrBf6J9hsaPgjTkaHf8364KUMm2','christian', 'kayonga'],
    ['oSz7BLoPVCZ9ehQvy6XeGEP53o93','aloysie', 'niyoyita'],
    ['ZDrYrtQE2WWGf2sYQMVRA5z9dRo2','noel', 'ndamukunda'],
    ['jXBc9CY3oTa6EN2R1jSnlsgJvZ22','lucie', 'tuyishime'],
    ['5SiOqBow2VTVFfV5UqLPd7vqAzp1','mireille', 'umutonisekamana'],
    ['VzinmaJkTqVzP6NL1t1zhxyGxAA3','abdou', 'kamanzi'],
    ['Hs6j33IRLuWGppfCeuC1Gx26Rx22','eric', 'rurinda'],
    ['MicqSbYDvkNsfxE2rkRZZ7qJZc23','fred', 'kaberuka'],
    ['8uR4nVG6hJXZrOWN5dABiKEr0Ee2','diane', 'ishimwe'],
    ['XzW2dHssuNRcgxAXHiidm40zVi22','sixbert', 'shema'],
    ['wqBN8iibouaF6mv4VgWATJisF5f1','valentine', 'nishimwe'],
    ['B50k2NHxtPdEXx9lWWqnE7a14Bu2','fidele', 'maniraguha'],
    ['taXoWpXP5YXvmIcrqbaXNyNkaAD2','patrick', 'tuyisenge'],
    ['Pc1cq4E0o4eeAf0kCUkN9xjiNhq1','jean', 'dedieuuwayezu'],
    ['nsFRwxsAHDfqwCKGFRj85JGgwAj2','eric', 'kirezi'],
    ['sbADit7rXAfpKGeKUlfnaNVGwHy2','elithe', 'redemptainara'],
    ['EQP4jeqqThO2MHyfSrZntvooQpP2','dorothee', 'karehe'],
    ['iMHET8lGM5UUiXCEVNsogqTp5IW2','francois', 'imanayumvabayo'],
    ['bY7CEpl8FpPmZb67RUK4VZYLrXt2','henry', 'markrugaba'],
    ['cjQHwKSLltavR3c3d4xE29AVfWJ2','eric', 'ntakirutimana'],
    ['Ew5qt1u4I9ZYCEmj3ud2OfDi4AJ2','hyacinthe', 'mushimiyimana'],
    ['WoN8ElKHJhMnC1yPluTLwUEGdk43','nadine', 'jessicaumuhoza'],
    ['O4TNPzRqNfhVfHLkSj9Ghh8uQRa2','fraterne', 'mutimanama'],
    ['owz54idEjFODpTWzA8Wnmh14whp1','magnifique', 'mukundwa'],
    ['SvjoasxkhDNprQKzGHdJggO74pq1','diane', 'clarisseuwibambe'],
    ['fXL1lYSNgCaG5EfOZBDopzDnAcf2','jean', 'paulishimwe'],
    ['cnKc2E7Ag2NqMZUY84YS6fHiV8H2','hamdoun', 'twagirimana'],
    ['yYqeaSL2kAaIp3ly8C6VMeWbQ8W2','barbara', 'umuhoza'],
    ['vQi5lYiHiyWWuCjYX2tS5halvxR2','pie', 'celestinhakizimana'],
    ['ehNRltNKBLXmWk0x00fHbnypiaD2','jeanine', 'nyiramana'],
    ['fg7phSDCHTdxFYtwJiJicouHhUq2','patient', 'nshongore'],
    ['ZXmVyKVepWbnN6yEUyZxcxAAnyb2','rhona', 'tumushabe'],
    ['aVZNzeWZRtZ1vq3LPBmCey3puGV2','bertrand', 'rutagarama'],
    ['4kmwpbOnIMVhiBEy3HXLMxGLvc23','godfrey', 'mutsinzi'],
    ['gzInsJEFbaPDhBFOhzXo9AsnaM12','alice', 'benihirwe'],
    ['6OjrL8w9wNfZ6q8fgQCM5z0n4CI2','xavier', 'nyandwi'],
    ['5Ct3jmoteXPTjBham0frYEVlA493','assumpta', 'cyuzuzo'],
    ['xE4Z5PRP4fNGWHGiGNGMEoPHM342','claire', 'akamanzikaneza'],
    ['rQnHBOeo34cYHFwjIYLRk1nZOgK2','annick', 'izabayo'],
    ['hgqKuoMHaGZX58nmXqBSM71UOVj1','vedaste', 'nizeyimana'],
    ['dU4FVIMLCgNY9EuZuwhOKCVGEHg2','thamar', 'gatesi'],
    ['9As65I1Y1edWo9v9uGPSSc5bwDI3','billy', 'gilberthabimanacyusa'],
    ['dDIabondjZSsUCBGWAJpfQipqam2','irma', 'girimbabazi'],
    ['kH5qmEG52adIkLODbTc5JXALtjg2','vanessa', 'ingabire'],
    ['VRhuZs6VgiOshwTGbl30VWtdoHh2','ingabire', 'dianehirwa'],
    ['JLoX5xCigmN7jGs3Iv97uypgM5i2','steven', 'mucyo'],
    ['qFDWhx7sCvNyUWqIJS2qM3bJ2q93','carine', 'kalinda'],
    ['ZvSvZHLTBxSjBEdI9wdJJ3IjYf62','florence', 'niyigena'],
    ['BVC5ynVW4uMcJgTrwx22bKNcUeF2','jean', 'paulniyibizi'],
    ['k7acicMRSIWXdjC2DuCfUmDj5oV2','clarisse', 'impano'],
    ['5RIUKj4fQXXNJrJ2lyN8HLkjNz13','denise', 'murinzi'],
    ['uh6bw32rlNQ2ZskDCJhM0iZrd8p1','eric', 'gasana'],
    ['UkxBMkstWAdVv1ssBZUGSqKfMBz2','rosalie', 'mukeshimana'],
    ['gIEeX4oWBSf0IO5qg2AK5SM6Cyu2','gustave', 'niringire'],
    ['sofuXzVMRnUuVUi2nANRPRPKZRf1','jessica', 'irambona'],
    ['PUAmwzJ2j0Y2orRqyTqNOYKjdoH3','emylie', 'gahimbare'],
    ['GdAnUkFTpQZz8eKyW3HCfP2JJNd2','eric', 'ntaganira'],
    ['RetC76LE7Xc6gQFX2PNHkIPgdZx2','herve', 'rurangwairadukunda'],
    ['LfUfWabMFAh9DBGCf8CNN14C2aG3','redempta', 'ingabire'],
    ['cRrD1XOsVPTMPETcJ3ZgaDXwWkd2','francois', 'regisniringiyimana'],
    ['8GFAUjaFGHNSZcDzxfK5dJdFkWi1','angelique', 'ingabire'],
    ['4jJOP33Sh6OHKMiB2aUx1Mgk8b92','olivier', 'mutabazi'],
    ['DfC46xVaNvW8iENhuAIhDQz7hfz1','petrine', 'muhoza'],
    ['60XXbdIpiPdmQHSfAObOIETEEKr2','elie', 'mandela'],
    ['ORjXoWA8DxQ9yNlRAGDJdC4Kpyt2','leon', 'habineza'],
    ['kuBWKjL5VYRv3Ekp6m3tkswHQnB2','benjamin', 'cyuzuzo'],
    ['9oNHf2ZBTfUE9NZJz8hEvd5M4is2','martin', 'hubertikuramutse'],
    ['5G8rzw2IFsVzWRW5fJIORtYIKZ63','joyce', 'rulinda'],
    ['JDBpuuk7cnX4DxtPgx0UEeMYTii1','marie', 'claudineumubyeyi'],
    ['tYvWevsWk2VlSot9rQ8RjjVDBHO2','christian', 'muhire'],
    ['ICdy8T77phaULnDrldmGxQdg4h03','dativa', 'kabatsi'],
    ['tPvr9A2UqYb3KL35wlDfDQFeTCv2','ross', 'erickarambizi'],
    ['K4Vhaq3z4yU2BhrNsLeBrRE6lSx1','deogratias', 'nshimiyimana'],
    ['ljY63fPr1FeBxjsIrUnv1IZLEME3','afrika', 'prudencehabinshuti'],
    ['yMqp3NgXtPWmwO1yusXbu7mdAQ92','lucie', 'dusengiyaremye'],
    ['D1H82YNwZScXVwT6RBqP98zTesj2','grace', 'umuganwa'],
    ['4fS3iv7KL3g9x0fLh5J9V4Znvzl1','josiane', 'uwamahoro'],
    ['mpizaSo09UQBymz9tTPO5u1QDzJ2','yvette', 'umwali'],
    ['U6oATk8RzWSfPFkQvhnZLpRmIPG2','morris', 'kayitare'],
    ['bW4bk4TOE5Uj5pZzwr4SM6QdGK72','egide', 'sakindi'],
    ['4tGKmDzfyYUhaO60MQkoxOlZOsb2','fabienne', 'mutamuriza'],
    ['U64XfHE8YGauVf4JgzxrUpFI2zf2','protais', 'nkundineza'],
    ['SylnJsFwO0PQe5qdennITwrQIpo1','marie', 'auroreniyitangamanzi'],
    ['a35nWOpXhAc20l9igvbt3MBVkWH3','irene', 'nteziryayo'],
    ['FwYJjwQcGTU094JSNh7ZUFzfXrl1','marie', 'rosemuhoza'],
    ['YvLwVHnUDNh5bOZ9vD00iHPiNRJ2','orly', 'mugwaneza'],
    ['goZMnki9O5P5NSd41CVr8bp9iOx2','jonas', 'niyogakiza'],
    ['fwKqNYhmc2MZy0XDT8Pjp1qVrbU2','kellia', 'umulisa'],
    ['IwKhD5z3HwM9CrlRjLG1YQdJ97s1','private', 'dukundimana'],
    ['9krdiGYclkcM4h2FQHgA6eQ6CEr1','narcisse', 'mutanguha'],
    ['vaShSkiEPmMRyhuJabEm5gn5nrb2','yvette', 'amahoro'],
    ['1nD2Z5E8yhdK3hsP5ILWd9uTZAR2','jacqueline', 'bamurange'],
    ['cjSEV67ThndZKruef5PhobwEOPD2','camarade', 'samuelamerika'],
    ['a9GjWuZxMqeo2ZlHa8De9h7mCXr1','alice', 'uwera'],
    ['6zGt1KunpzMAszWO8eSm6CEswGF2','frank', 'karengera'],
    ['gHNIupXP05QuRQ6C0fvBF5jekTG2','charles', 'mwizerwa'],
    ['BvsCp7k4gfTBArz9pvSXPpT3W2A2','grace', 'nyiramatungo'],
    ['d2aHFIPQuMdaeAUOeTVRSQc1Wxr1','angelique', 'muhawenimana'],
    ['x5XvEpSxr3UHlc19BM0qycmFhYD3','celine', 'mukantwali'],
    ['fRyRxAK73IRN2mV3QMSnSIwkTCm2','emmanuel', 'musanganya'],
    ['MobWS8Qn29h88aKBg8pGXLe97eP2','jean', 'dedieuuwihaye'],
    ['ThLliMbGpWTMbeZ9FkgzdmtfzPH3','francine', 'irankunda'],
    ['gf4Gb2LDU8QkHBbHcGjdCW5EzfO2','christophe', 'rukundo'],
    ['YIuUh9vfReWNCgD7SUWD6LTs22o1','marie', 'assoumptaumuhoza'],
    ['V76NPg3WUHhkN46dmJFNACvsKO13','fabiola', 'bagorora'],
    ['8a8Rai5yuiXZLSDkjKHHx4LdB3C3','joseph', 'elvinkatete'],
    ['eWZ1SR6v49S1lKwxlU1JXINUABf1','joel', 'mugisha'],
    ['iOnTVwsCnjhJb0YczGibm5bWma03','sandrine', 'uwiduhaye'],
    ['T3NmqeLtSGRQ4xYRlE6HuiqvE6q1','arlette', 'saroniyibizi'],
    ['44OqyR9zXCUHvGX4CqbO5HLxd6k2','emma', 'roseuwimana'],
    ['FloGxULWvyV4xbhz0mzDhKPWI902','francoise', 'uwineza'],
    ['z74DoqLDWVTlzcmgn4O0tC4U36e2','clarisse', 'uwase'],
    ['xVtFrFd36Bd3lmczVe9eqEAwOBk2','rachel', 'cyuzuzo'],
    ['T6HfbHFS5pSzHgjZK7wvVtQvuwE3','chantal', 'kabatesi'],
    ['1jKTCcOqynUsgoHMvXswMD18wjN2','theobald', 'nshimiyimana'],
    ['3fz07KTT4YhzM4maY2yIN5UQoLH3','elisee', 'dushimimana'],
    ['mZsuafpB4VVTqoT7Wu7lamNOzdg2','assuman', 'muhire'],
    ['hXW97CLtcSZNVoRVLucssHNq1oo2','susan', 'teta'],
    ['CtawYAk1TZaTPtVvoM8HSyeQQC93','emeline', 'hategekimana'],
    ['DGmLngKCIwd7KILLTjAwrScWvOA2','ben', 'dedalesixtehigiro'],
    ['cD6uqYezKCZikw7rcl4UI5Bs3px1','rene', 'francissimbimvuyekure'],
    ['GhdwiDjY3bPewYkjRfvCRrmUBhb2','angelique', 'kwizera'],
    ['GF3ZdoRSU8VA0bZnTQDjk6XkY9w2','bernard', 'uwayisaba'],
    ['Hl8Wa0kB4PM6RXf5v5fqL4TERhW2','joseph', 'uwimana'],
    ['3pngB0jrbZaS0ey8SSaSXeaAs2C3','rosine', 'uwantege'],
    ['PciY4C9I8BgVyikEVgi320f2NvQ2','liliose', 'umutesi'],
    ['cbqX2qIz5IPcRNcSPIv4PYsoif52','jean', 'ericcyizamugabe'],
    ['KWPYV39EjoeuVkMXRnFQ9JhDgF02','geoffrey', 'mugisha'],
    ['KgQiCbrOyje6wXVbNnTz4lBD2e43','jean', 'paulhabimana'],
    ['H7eBONDqUvSBONM4UM91P2rXE8B2','stella', 'mukakalisa'],
    ['lHGv2wQN1gOoZcX4dSccVjtSVwJ2','olivier', 'duhoranimana'],
    ['ssRA4Ew3k6fgZmeoHy4Om2pey3S2','yvette', 'umugiraneza'],
    ['WYrzoCZxbPgsytTRqg7eWJwsZDx2','charlene', 'kanyange'],
    ['jDVwdrmSUfMK37IIu7U4qTLbZU23','innocent', 'mushamuka'],
    ['TCNmHrca22b0ZRxyleYd0DVQrSG2','alexis', 'gisore'],
    ['nKjQ44ORIFbF6LUgjOp2DJVa8uv2','joyce', 'munezero'],
    ['B6NNflAultX163gBPobPpa2PU4O2','geraldine', 'mukantabana'],
    ['VTF1WP7f5of3HCVHlGIOKTQI3V03','honoree', 'victoiremukashema'],
    ['en3FSfTxf8Q75KjtizHwTJmIrE62','anitha', 'uwingabiye'],
    ['tV9aiuhUpwbDxh4FWKYbh12WQvk2','betty', 'mukankusi'],
    ['oQYUpgtkNFMLVrnTd8mZrniYdNx1','jean', 'bosconsengiyumva'],
    ['a3uw5AXwzNWdisFwjXfZ6Vrjn1B2','emmanuel', 'twagirimana'],
    ['Vl1xKJbz0xeTcxwLnetiV34qGSB2','marie', 'aimeeuwera'],
    ['GJZ3YLSuy4akaLprWfcZTw6pFMj1','salwa', 'uwabasindi'],
    ['idE49l46qJUZPMrgjjVurYmrHGk1','david', 'ndayisenga'],
    ['FZJSkC1SNgg8p59kd7JWjnWonAH3','flora', 'umulisa'],
    ['goBMQbpASXPuHlmuMCFKdb0MvHv2','jean', 'ntawanguwe'],
    ['aemEMLeeFiM0RESjGUwK8V2X65v2','evariste', 'nizeyimana'],
    ['BS218fQiLKdgu0ECgGDJ4nSIUe53','pascal', 'habineza'],
    ['mAXPSA9d2ngAwlL13r2U8aVYAGt1','dorcyne', 'nishimwe'],
    ['ByuWTeJs5RWTWSx1jjC2AD7cj483','octave', 'gakunzi'],
    ['N6T0jJA4rGYXJ7PzFzSxsSxdn7F3','christian', 'rwabununga'],
    ['yRnR21l4LjbmRTKAR4VSoKZhywE3','rosine', 'nishimwe'],
    ['RioZOUgVdIdN2FYk4EAJQ1oaBuL2','perpetue', 'dusabimana'],
    ['zdFCVEZS4EcVG5fYcodCMbCIGps1','yvette', 'nyinawamuntu'],
    ['Kb2FvU3nE1Vy7NQUVb1XbOuObm53','sharon', 'uwineza'],
    ['jIP6tKuXfsMZ1tHeoipYC1LbzPM2','egidie', 'nirere'],
    ['8SDzO28h2jRzwUCdFDJBOXhgnw03','yvette', 'abijuru'],
    ['1F2ZnwvfHYXE37SxUt1m0VYepto2','ntegana', 'musirimu'],
    ['prDPf0MCntMjzy51x3kBkyshxc73','clemence', 'nduwayo'],
    ['XRtMWYwOKIZFKemHhQelxdktWCX2','christelle', 'uwimana'],
    ['1LZNyqLMeFUgoI4CsRgebRIjRx43','alice', 'mukeshimana'],
    ['pEsPaYU6FHaZAgytmzoV66fSEs13','theophile', 'nyirimana'],
    ['hCtoNjjKJZXwBxatCWBdWEGh5D02','justine', 'mucyo'],
    ['JOnonfdTsafc8q1Vy0AD0vhK1bi1','elisabeth', 'yambabariye'],
    ['eUTsvTNd5TPeSdCF6WRp83eoNEj1','nadine', 'tuyishime'],
    ['EBE3HM1AG4QZHtf1Kq6ly2h9r5u1','euphrosine', 'mukankebukande'],
    ['M2i4pfLVICQvi78ZGPoUhg2oYO92','answar', 'twizerimana'],
    ['E9dNBKA4OcNToqEpQOcQ6cI9LTk1','anne', 'mukarebero'],
    ['lXzXox0ACSV1QgDuhEcHKfevWwp1','betty', 'nyirahabimana'],
    ['eBOch2JPRqdsk7gAzq5BvJjXUUa2','anne', 'niyomubyeyi'],
    ['Kt2xd1fbf5RSGLSwXYgEKdQKXa12','jeannette', 'mireilleiradukunda'],
    ['9tKsUQEmmmX9PVJBVEAxI73G2ui2','bernice', 'iradukunda'],
    ['cLpix3nNF7fsNDinpIKsywosBeq1','jackson', 'ngiruwonsanga'],
    ['qBkPiplv19UBtZ54SvBQH3wLJ852','josee', 'uwayezu'],
    ['6goEQy56FiYIzGyhzfuKb9LaXnM2','donatien', 'majyambere'],
    ['ZeXqzrIuP2TdyefW6uJbWelp1DI3','richard', 'basanase'],
    ['CJBxSM6rGuhfp9GATZunbz8qDYG2','peter', 'muvunyi'],
    ['QtL7H4DYTFWrXHzK0OlfcSC6s5m1','james', 'nkuranga'],
    ['YTEhcoLbC6YXSwRpsQPopo8PXiU2','juliet', 'nyirasafari'],
    ['Kb4sYR6wyYQeF2eXMmq3MFKaSoG2','esperance', 'uwitonze'],
    ['uNzcYzN8eHbGMFQCILB0IfmBLVA3','grace', 'uwase'],
    ['qsf7WPrn0ag0AuYgExuJKxXixO33','aline', 'mukakayumba'],
    ['sNStkIBIY5TrpxXaQFiZTlMfLuB2','denys', 'buhake'],
    ['jtikfsO0rLXSHB4ufKPUsMH2ZiI3','pauline', 'kezakimana'],
    ['xHGsMsLV0BQZPGKlw3oBvm6vknB3','gaspard', 'nzasabimfura'],
    ['z8oxfR9I51aVHC34gm9oyG0iloD3','diane', 'ingabirehirwa'],
    ['bDaonuleKvSkh9ydLYP4poyHNSi2','sylvie', 'karemera'],
    ['nCG25v6dojRMGwP2BArNiLUcxwo2','claude', 'mudahemuka'],
    ['1BAtj3wTKMheOD7LBCwULsuljtJ2','dieudonne', 'tuyisabyimbabazi'],
    ['mzslJivINYVBswLVZh2agFZNj852','blaise', 'musabe'],
    ['yYXrbY1kcXZr5snoO7ynqmwTJn03','rebecca', 'tuganeyesu'],
    ['P8gov1ataWbyBGBan0UM5YZ4fqv1','clemence', 'tuyishimire'],
    ['PG5DwSNgoobmyvd5OlSMP2bi8JA3','gloria', 'igiraneza'],
    ['GarJ8P3oQmXSSxCUCvVPSN3KmYW2','christine', 'nyirandikumana'],
    ['CA6XqLcy1nep4ZxrOzoHlHW16a42','etienne', 'babuzindunduro'],
    ['mRaMZCtarAYCKl2qCkdrhFXH4KN2','leatitia', 'mukeshimana'],
    ['sKBi6G5IjnQ2ePQqwJBOglql0uM2','vital', 'habimana'],
    ['uVfrMgUy3OOtqz1vZIsFzy5wrgM2','hyacinthe', 'kakuze'],
    ['kE3P6lpuBBO9mEckGh0QFZTJlA73','aphrodis', 'nshizirungu'],
    ['4SHl3xICmwhp62HTjkynrPIlEBv1','patrice', 'nshuti'],
    ['rcZpNDFNl0TqolpHrZUKy6VJeqB2','angelo', 'igitego'],
    ['6qWE01Sr52dM18Z1JoICjz0Ca4J2','muhodari', 'kadugano'],
    ['7DmDVzda5kYKHdCT2JcQjIDYyS63','jimmy', 'ruhanga'],
    ['oeVG5ntvqRaEUSiRiyzVxnAN5R73','sylvia', 'ingabire'],
    ['GsAqMe9HXHgxeRdBvjL5bijiEPo1','yves', 'fabienkarasira'],
    ['LNWkv0PZv1Mko2MHpOoPRYnlnt82','denise', 'kayitesingamije'],
    ['al3GIRX6E9dJmGhidfz8LawqGN62','magalie', 'ntahokaja'],
    ['AWfBnhLlQcb6LUy9F8bbhZPyxx73','consolee', 'bagwaneza'],
    ['3OQ5JRjmzAXbHXkftkgBb7LqJAY2','adrien', 'gakumbahabimana'],
    ['hFcZXvafSiZgvG4yqjUJvprVXx62','ariane', 'merciisimbi'],
    ['Y3G5FgnAxyLhTDeLKSSyNFmfA3m2','olivier', 'mutijimana'],
    ['NJQUbAivSZXV8oykPxPP46wBvUx1','sandrine', 'uwamahoro'],
    ['q94gily06qSO4jI3OV821NqXMKn1','joseph', 'murinzi'],
    ['uKAjUvbie4XVqd13vDgk26ka3ow1','herve', 'nyirimihigo'],
    ['M68Lvg4bJtWfiPe86uY250TZGmk1','norah', 'natukunda'],
    ['CpHQgd40bFfXk9Hu3AqQ4TvbWpz2','tresor', 'kambanda'],
    ['KWo0LaCp9vWrSf1Xtr8ubjUhXMk2','jean', 'baptisteiradukunda'],
    ['2Z51859vclTas8SkD5vgme573mI3','emmy', 'kangwege'],
    ['CuKDTMIDrqh4bRNi89RR7vELCNq2','alice', 'nibakure'],
    ['SK14YzyNM0WZy2YOGUwrUzhTEZQ2','evelyne', 'mutuyimana'],
    ['kGSxlsTVYuVViL6VtvPydYykVK13','sonia', 'hirwa'],
    ['8WnEu6IlZpOkoSZvlFUfLkeJfs62','raissa', 'kamaliza'],
    ['Nn3JLUZDa0SaKppm5dWjy1FbrRx2','aime', 'laurenttwizerimana'],
    ['QZ2AKqR0LwhEzJxue6jOJ6bygyF2','nadege', 'umurutasate'],
    ['kTnnfnScKIdKzT1O4XMKqtMXv3K3','francoise', 'uwiringiyingabire'],
    ['1jI7keHXXGhME9Z7qWAjmqOoI2u1','valentine', 'mutamulizambayiha'],
    ['yFXxk0hX45hu7wbJSQguGFvI9QD3','anicet', 'nsengumuremyi'],
    ['XXhtEnE1tlVaqeceZ7CcsABvo3a2','therese', 'uwamahoro'],
    ['zkdxOa95TEeYfaYxeIr1LSFnF1p1','samantha', 'mugabe'],
    ['00Iyw1wEcfRO56sqMTi31a5L8oD3','scholas', 'buranga'],
    ['dorsyN522oOZPsgB6n6EDm5XFNh1','jean', 'baptistenyaminani'],
    ['vS6BuS2FLiSVRjm5LxnoU2ITacO2','fred', 'mukunzi'],
    ['OHj6HpTgXahh3uYViqNo5hSxMSB3','solange', 'dusabiyera'],
    ['8G9NRLeiega3axoS1fSFDPWZhWT2','josiane', 'nishimwe'],
    ['kKbr50lFpXcaEiJibPAMMuxmaGg2','olivier', 'pacifiqueniyomugabo'],
    ['fGJc3YCxu5O9vNGKKptkB4F2IHM2','manasse', 'twagiramungu'],
    ['Pu9PHaKpa6Qhr5y4TZUSj56Xy0o1','alliyah', 'kaneza'],
    ['a8MiByxng5Qd6rzWZjX0VVtl2Za2','emma', 'roseumwali'],
    ['IntTNvK2U8fQ9nrDoavN5mBio962','sonia', 'umutoniwase'],
    ['i8v6cnJSyHbpHDdPbujzfpXzX8B3','jean', 'dedieudushimimana'],
    ['p5rhpJKhPvYJKTViS6EtIqWYIIb2','gaudence', 'ndayambaje'],
    ['h8af7W6qXqVZ3U4nsxiO9SIx4Mn2','eric', 'karama'],
    ['YweBgvequTfOmPTYp10rfX4xmk53','marie', 'chantalmukantwali'],
    ['vdhvnlmsX4QLhWZgdhRcQpBv1YF2','blandine', 'umuziranenge'],
    ['y5T3woYPOuaI6xYwcYnmEL3ExSf1','etienne', 'musemakweli'],
    ['sEUpdS9MN6XSgYlF188zMxOeve53','alice', 'neza'],
    ['Xs2xEVcRmtPkYuABHosuja3FLPX2','norbert', 'kwizera'],
    ['4NdGYNShG1MIAXKwzujXBsebv6s2','jean', 'boscohakizimana'],
    ['n1Bouk3050NIuBUhZy5tKslvvNs1','jean', 'claudenshimiyimana'],
    ['TecaSOOPycYPo1hZ3CPaNWT8qOk2','emmanuel', 'brunondayisenga'],
    ['jqZkxCkrMxUYvAZEGvAPAqD0IVx1','faith', 'mutesi'],
    ['SF5GTBb2OoZ8REFE7fh2deIWjek2','florence', 'sumwiza'],
    ['tDNDnvrM38TMfcybEQIqgenr1KP2','solange', 'uwingeri'],
    ['QlMGpgU0sKbZqpr30VjYdP5AtA42','nshuti', 'samantha'],
    ['Ls3tbdinJkTo5QwYVLDj9ETlxg13','pacifique', 'kwizera'],
    ['9pu3ICGvImbadOzbGpexmcXVPfu2','jean', 'claudeturatsinze'],
    ['HQopv1BuO8NbOQ4SB9C0eGjBbHY2','anitha', 'uwasesendakize'],
    ['wniKeXKindNQfotodT2i1nPEqxe2','violet', 'kagabirwa'],
    ['DYD4xLzWU8OWvVwBq2I0ONqOpt22','tharcisse', 'bizimana'],
    ['4F4bf2P2fVgz1XdBO06IGsbMsph1','flavia', 'kantengwa'],
    ['EfqGVQeHbiUAXNqojIRvm9Fqaen2','emmanuel', 'twagirayezu'],
    ['wMjm4n6DCKQ22URtiCKecEU2qvh1','josiane', 'mukayitesi'],
    ['ILViICD7wjbd2OYkbFpyZFQqFNo1','pauline', 'kimenyi'],
    ['y4xcdRn1fEgs2IWI0DSlq9OQkQz1','patricia', 'ingabire'],
    ['d2C1bg5brSgK3jlFOTpNQ4uhUBs1','pie', 'nkubito'],
    ['gJ5aKF3cj8Xy3V6g4Y1Zsz9sTHA3','divine', 'nikuze'],
    ['Goc8oWwvlYMZNBTGzSo00Jrq7853','raissa', 'mugisha'],
    ['fX35ZGfJgWTp9vvw8StkXrcdao83','shakila', 'umutonikamatali'],
    ['UkuHfGAJSUQ7u1Zi5uX9eaYfV3p1','amandine', 'karire'],
    ['Bw04mKRZ0wRWL0GWqySoOyKqrVu1','anita', 'mamenero'],
    ['JLpMjOI4KWSi8zjap6WgL00fjED2','gloriose', 'ingabire'],
    ['HpqZ9xAR1mUfNmQpDgh60ajACsf2','liliose', 'mukeshimana'],
    ['Vp0H8Yrk9dPiIYFluLjmHtOIhAu2','leonille', 'mutambarungu'],
    ['IgAgXFVi6OX1BxqKmE4Q2ZW7LNQ2','bernard', 'nkurunziza'],
    ['JOOLZxjfONSsBTbzytKBq9QWQsN2','john', 'nshaija'],
    ['a2QP14NHyTRxAPC8H9BnMQtOqiR2','rosine', 'uwamariya'],
    ['vXjHSL6ttuVw6AW81hjt4kuqofH3','constantin', 'bihoyiki'],
    ['w01CXRodzUSlqMQJh7AxbCft4Tr1','rodrigue', 'bukozi'],
    ['kgZlQ8qwPogPkPLhJVGqIvJzBIj1','clarisse', 'mukundwa'],
    ['XXDLWCHhD9SOM7PejMruWbMMsAS2','jean', 'claudendayiragije'],
    ['PVjBSVxGndanGoZ1EWsqZvWOcAc2','geoffrey', 'karara'],
    ['GtMVZzjZglfeDJu0tXsrJH3o6z73','joseph', 'nsengimana'],
    ['xb4UIQ9AnjakVCP5IPwdgXhAyjw2','leontine', 'byukusenge'],
    ['6qSl7qEPGUeTWXSSzHeWW1vfAmH3','sophie', 'akimana'],
    ['mCPXkiado7a5haOSzQIrGrB9Plz2','clarisse', 'kazayirwa'],
  ];

  static const List<List<String>> ids2 = [
    ['Xbvn7UtlLlfNj4Z37bFtgEH1VJm2','Enumerator'],
    ['WoN8ElKHJhMnC1yPluTLwUEGdk43','Enumerator'],
    ['g7DFyTqvS6VmF60KUvlexc0yLh12','Transcriber'],
    ['KJzeDxdWyaSkI9DcGevKv1HJbBT2','Enumerator'],
    ['YIuUh9vfReWNCgD7SUWD6LTs22o1','Enumerator'],
    ['eFtEOfONiUe1bMsYHZisl3IllTM2','Enumerator'],
    ['pEsPaYU6FHaZAgytmzoV66fSEs13','Enumerator'],
    ['B50k2NHxtPdEXx9lWWqnE7a14Bu2','Enumerator'],
    ['iMHET8lGM5UUiXCEVNsogqTp5IW2','Enumerator'],
    ['jIP6tKuXfsMZ1tHeoipYC1LbzPM2','Enumerator'],
    ['fXL1lYSNgCaG5EfOZBDopzDnAcf2','Enumerator'],
    ['dorsyN522oOZPsgB6n6EDm5XFNh1','Enumerator'],
    ['w01CXRodzUSlqMQJh7AxbCft4Tr1','Enumerator'],
    ['ehNRltNKBLXmWk0x00fHbnypiaD2','Enumerator'],
    ['gzInsJEFbaPDhBFOhzXo9AsnaM12','Enumerator'],
    ['fg7phSDCHTdxFYtwJiJicouHhUq2','Enumerator'],
    ['hgqKuoMHaGZX58nmXqBSM71UOVj1','Enumerator'],
    ['dU4FVIMLCgNY9EuZuwhOKCVGEHg2','Enumerator'],
    ['UkxBMkstWAdVv1ssBZUGSqKfMBz2','Enumerator'],
    ['dDIabondjZSsUCBGWAJpfQipqam2','Enumerator'],
    ['ZvSvZHLTBxSjBEdI9wdJJ3IjYf62','Enumerator'],
    ['sofuXzVMRnUuVUi2nANRPRPKZRf1','Enumerator'],
    ['AWfBnhLlQcb6LUy9F8bbhZPyxx73','Enumerator'],
    ['n1Bouk3050NIuBUhZy5tKslvvNs1','Enumerator'],
    ['60XXbdIpiPdmQHSfAObOIETEEKr2','Translator'],
    ['9oNHf2ZBTfUE9NZJz8hEvd5M4is2','Enumerator'],
    ['cjQHwKSLltavR3c3d4xE29AVfWJ2','Enumerator'],
    ['mpizaSo09UQBymz9tTPO5u1QDzJ2','Enumerator'],
    ['U6oATk8RzWSfPFkQvhnZLpRmIPG2','Translator'],
    ['6qSl7qEPGUeTWXSSzHeWW1vfAmH3','Enumerator'],
    ['YvLwVHnUDNh5bOZ9vD00iHPiNRJ2','Enumerator'],
    ['IwKhD5z3HwM9CrlRjLG1YQdJ97s1','Enumerator'],
    ['vaShSkiEPmMRyhuJabEm5gn5nrb2','Field Coordinator'],
    ['1nD2Z5E8yhdK3hsP5ILWd9uTZAR2','Enumerator'],
    ['cjSEV67ThndZKruef5PhobwEOPD2','Enumerator'],
    ['BvsCp7k4gfTBArz9pvSXPpT3W2A2','Enumerator'],
    ['fRyRxAK73IRN2mV3QMSnSIwkTCm2','Enumerator'],
    ['yYXrbY1kcXZr5snoO7ynqmwTJn03','Enumerator'],
    ['8a8Rai5yuiXZLSDkjKHHx4LdB3C3','Enumerator'],
    ['taXoWpXP5YXvmIcrqbaXNyNkaAD2','Enumerator'],
    ['iOnTVwsCnjhJb0YczGibm5bWma03','Enumerator'],
    ['44OqyR9zXCUHvGX4CqbO5HLxd6k2','Enumerator'],
    ['a2QP14NHyTRxAPC8H9BnMQtOqiR2','Enumerator'],
    ['1jKTCcOqynUsgoHMvXswMD18wjN2','Enumerator'],
    ['gf4Gb2LDU8QkHBbHcGjdCW5EzfO2','Enumerator'],
    ['mZsuafpB4VVTqoT7Wu7lamNOzdg2','Enumerator'],
    ['CtawYAk1TZaTPtVvoM8HSyeQQC93','Field Coordinator'],
    ['PUAmwzJ2j0Y2orRqyTqNOYKjdoH3','Enumerator'],
    ['Vp0H8Yrk9dPiIYFluLjmHtOIhAu2','Enumerator'],
    ['lHGv2wQN1gOoZcX4dSccVjtSVwJ2','Enumerator'],
    ['en3FSfTxf8Q75KjtizHwTJmIrE62','Enumerator'],
    ['tV9aiuhUpwbDxh4FWKYbh12WQvk2','Enumerator'],
    ['oQYUpgtkNFMLVrnTd8mZrniYdNx1','Enumerator'],
    ['yRnR21l4LjbmRTKAR4VSoKZhywE3','Enumerator'],
    ['RioZOUgVdIdN2FYk4EAJQ1oaBuL2','Enumerator'],
    ['prDPf0MCntMjzy51x3kBkyshxc73','Enumerator'],
    ['NJQUbAivSZXV8oykPxPP46wBvUx1','Enumerator'],
    ['eUTsvTNd5TPeSdCF6WRp83eoNEj1','Enumerator'],
    ['EBE3HM1AG4QZHtf1Kq6ly2h9r5u1','Enumerator'],
    ['E9dNBKA4OcNToqEpQOcQ6cI9LTk1','Enumerator'],
    ['eBOch2JPRqdsk7gAzq5BvJjXUUa2','Enumerator'],
    ['Kt2xd1fbf5RSGLSwXYgEKdQKXa12','Enumerator'],
    ['Ls3tbdinJkTo5QwYVLDj9ETlxg13','Enumerator'],
    ['XzW2dHssuNRcgxAXHiidm40zVi22','Enumerator'],
    ['CJBxSM6rGuhfp9GATZunbz8qDYG2','Enumerator'],
    ['QtL7H4DYTFWrXHzK0OlfcSC6s5m1','Enumerator'],
    ['uNzcYzN8eHbGMFQCILB0IfmBLVA3','Translator'],
    ['jtikfsO0rLXSHB4ufKPUsMH2ZiI3','Enumerator'],
    ['1BAtj3wTKMheOD7LBCwULsuljtJ2','Enumerator'],
    ['PG5DwSNgoobmyvd5OlSMP2bi8JA3','Enumerator'],
    ['z8oxfR9I51aVHC34gm9oyG0iloD3','Enumerator'],
    ['DfC46xVaNvW8iENhuAIhDQz7hfz1','Enumerator'],
    ['6qWE01Sr52dM18Z1JoICjz0Ca4J2','Enumerator'],
    ['7DmDVzda5kYKHdCT2JcQjIDYyS63','Enumerator'],
    ['oeVG5ntvqRaEUSiRiyzVxnAN5R73','Enumerator'],
    ['T3NmqeLtSGRQ4xYRlE6HuiqvE6q1','Enumerator'],
    ['uKAjUvbie4XVqd13vDgk26ka3ow1','Enumerator'],
    ['CpHQgd40bFfXk9Hu3AqQ4TvbWpz2','Translator'],
    ['XXhtEnE1tlVaqeceZ7CcsABvo3a2','Translator'],
    ['ORjXoWA8DxQ9yNlRAGDJdC4Kpyt2','Enumerator'],
    ['00Iyw1wEcfRO56sqMTi31a5L8oD3','Enumerator'],
    ['Goc8oWwvlYMZNBTGzSo00Jrq7853','Translator'],
    ['3fz07KTT4YhzM4maY2yIN5UQoLH3','Enumerator'],
    ['OHj6HpTgXahh3uYViqNo5hSxMSB3','Enumerator'],
    ['mECztum2IxeMnE5ZgiFAWF8HXG93','Enumerator'],
    ['fGJc3YCxu5O9vNGKKptkB4F2IHM2','Field Coordinator'],
    ['9PM2QQ1TL6TtbjqIc1fRj18gtzF3','Enumerator'],
    ['YweBgvequTfOmPTYp10rfX4xmk53','Enumerator'],
    ['y5T3woYPOuaI6xYwcYnmEL3ExSf1','Field Coordinator'],
    ['zkdxOa95TEeYfaYxeIr1LSFnF1p1','Enumerator'],
    ['O4TNPzRqNfhVfHLkSj9Ghh8uQRa2','Enumerator'],
    ['V76NPg3WUHhkN46dmJFNACvsKO13','Enumerator'],
    ['9pu3ICGvImbadOzbGpexmcXVPfu2','Enumerator'],
    ['8WnEu6IlZpOkoSZvlFUfLkeJfs62','Translator'],
    ['blCWLCfD5TNHLjk1Io7VD3aHx9A2','Enumerator'],
    ['y4xcdRn1fEgs2IWI0DSlq9OQkQz1','Enumerator'],
    ['cnKc2E7Ag2NqMZUY84YS6fHiV8H2','Enumerator'],
    ['3pngB0jrbZaS0ey8SSaSXeaAs2C3','Field Coordinator'],
    ['JOOLZxjfONSsBTbzytKBq9QWQsN2','Enumerator'],
    ['GtMVZzjZglfeDJu0tXsrJH3o6z73','Enumerator'],
    ['1LZNyqLMeFUgoI4CsRgebRIjRx43','Enumerator'],
    ['pkL45yLpIEeqr4ngbmKX0ff9DdO2','Enumerator'],
    ['JyMixoU1ILXf0kacGHQimTza2F32','Enumerator'],
    ['UqqnztoKCYYTbo3z1t9dkmB0yoS2','Enumerator'],
    ['4nc1O4Fk6WY9tonPAtjCwXq9xzx2','Enumerator'],
    ['VzinmaJkTqVzP6NL1t1zhxyGxAA3','Enumerator'],
    ['p8uFPSOEY0QYh6zvGiJgbWGRIrh2','Enumerator'],
    ['Zgb7m9R388c6fABHZ27B9May11B3','Enumerator'],
    ['aVZNzeWZRtZ1vq3LPBmCey3puGV2','Translator'],
    ['d2C1bg5brSgK3jlFOTpNQ4uhUBs1','Enumerator'],
    ['2Z51859vclTas8SkD5vgme573mI3','Enumerator'],
    ['Yl8icoVEIcSDduyLYG6lWaP49M92','Enumerator'],
    ['SrLAQvOGSvWxq9xXtAheFjKe5fL2','Enumerator'],
    ['vllUxLoXlZSuHedpMXxf3RxB0tu2','Enumerator'],
    ['RCm5scnJ5TT8EAO3mmuWfIT4xSa2','Enumerator'],
    ['KEk0uYxLOGhPgtAf7noPYVwhX6C2','Enumerator'],
    ['oSz7BLoPVCZ9ehQvy6XeGEP53o93','Enumerator'],
    ['WYrzoCZxbPgsytTRqg7eWJwsZDx2','Enumerator'],
    ['nKjQ44ORIFbF6LUgjOp2DJVa8uv2','Field Coordinator'],
    ['5SiOqBow2VTVFfV5UqLPd7vqAzp1','Transcriber'],
    ['Hs6j33IRLuWGppfCeuC1Gx26Rx22','Enumerator'],
    ['MicqSbYDvkNsfxE2rkRZZ7qJZc23','Enumerator'],
    ['8uR4nVG6hJXZrOWN5dABiKEr0Ee2','Enumerator'],
    ['Xs2xEVcRmtPkYuABHosuja3FLPX2','Enumerator'],
    ['nCG25v6dojRMGwP2BArNiLUcxwo2','Enumerator'],
    ['Pc1cq4E0o4eeAf0kCUkN9xjiNhq1','Enumerator'],
    ['nsFRwxsAHDfqwCKGFRj85JGgwAj2','Field Supervisor'],
    ['sbADit7rXAfpKGeKUlfnaNVGwHy2','Enumerator'],
    ['bY7CEpl8FpPmZb67RUK4VZYLrXt2','Enumerator'],
    ['owz54idEjFODpTWzA8Wnmh14whp1','Transcriber'],
    ['EfqGVQeHbiUAXNqojIRvm9Fqaen2','Enumerator'],
    ['wMjm4n6DCKQ22URtiCKecEU2qvh1','Enumerator'],
    ['yYqeaSL2kAaIp3ly8C6VMeWbQ8W2','Translator'],
    ['DYD4xLzWU8OWvVwBq2I0ONqOpt22','Enumerator'],
    ['ZXmVyKVepWbnN6yEUyZxcxAAnyb2','Enumerator'],
    ['P8gov1ataWbyBGBan0UM5YZ4fqv1','Enumerator'],
    ['4kmwpbOnIMVhiBEy3HXLMxGLvc23','Enumerator'],
    ['mRaMZCtarAYCKl2qCkdrhFXH4KN2','Enumerator'],
    ['6OjrL8w9wNfZ6q8fgQCM5z0n4CI2','Enumerator'],
    ['vQi5lYiHiyWWuCjYX2tS5halvxR2','Enumerator'],
    ['xE4Z5PRP4fNGWHGiGNGMEoPHM342','Enumerator'],
    ['9As65I1Y1edWo9v9uGPSSc5bwDI3','Translator'],
    ['kE3P6lpuBBO9mEckGh0QFZTJlA73','Enumerator'],
    ['kH5qmEG52adIkLODbTc5JXALtjg2','Enumerator'],
    ['VRhuZs6VgiOshwTGbl30VWtdoHh2','Enumerator'],
    ['JLoX5xCigmN7jGs3Iv97uypgM5i2','Translator'],
    ['P57tr4fThcWf1wWsDlBB6iunXnl1','Enumerator'],
    ['d2aHFIPQuMdaeAUOeTVRSQc1Wxr1','Enumerator'],
    ['k7acicMRSIWXdjC2DuCfUmDj5oV2','Enumerator'],
    ['5RIUKj4fQXXNJrJ2lyN8HLkjNz13','Enumerator'],
    ['z74DoqLDWVTlzcmgn4O0tC4U36e2','Enumerator'],
    ['gIEeX4oWBSf0IO5qg2AK5SM6Cyu2','Enumerator'],
    ['VTF1WP7f5of3HCVHlGIOKTQI3V03','Enumerator'],
    ['RetC76LE7Xc6gQFX2PNHkIPgdZx2','Translator'],
    ['LfUfWabMFAh9DBGCf8CNN14C2aG3','Field Supervisor'],
    ['BVC5ynVW4uMcJgTrwx22bKNcUeF2','Enumerator'],
    ['4jJOP33Sh6OHKMiB2aUx1Mgk8b92','Enumerator'],
    ['kuBWKjL5VYRv3Ekp6m3tkswHQnB2','Enumerator'],
    ['5G8rzw2IFsVzWRW5fJIORtYIKZ63','Enumerator'],
    ['xHGsMsLV0BQZPGKlw3oBvm6vknB3','Transcriber'],
    ['qFDWhx7sCvNyUWqIJS2qM3bJ2q93','Enumerator'],
    ['ICdy8T77phaULnDrldmGxQdg4h03','Enumerator'],
    ['tPvr9A2UqYb3KL35wlDfDQFeTCv2','Enumerator'],
    ['vdhvnlmsX4QLhWZgdhRcQpBv1YF2','Enumerator'],
    ['jXBc9CY3oTa6EN2R1jSnlsgJvZ22','Enumerator'],
    ['yMqp3NgXtPWmwO1yusXbu7mdAQ92','Field Supervisor'],
    ['D1H82YNwZScXVwT6RBqP98zTesj2','Enumerator'],
    ['4fS3iv7KL3g9x0fLh5J9V4Znvzl1','Enumerator'],
    ['kGSxlsTVYuVViL6VtvPydYykVK13','Enumerator'],
    ['bW4bk4TOE5Uj5pZzwr4SM6QdGK72','Enumerator'],
    ['rQnHBOeo34cYHFwjIYLRk1nZOgK2','Enumerator'],
    ['U64XfHE8YGauVf4JgzxrUpFI2zf2','Enumerator'],
    ['SylnJsFwO0PQe5qdennITwrQIpo1','Transcriber'],
    ['6zGt1KunpzMAszWO8eSm6CEswGF2','Enumerator'],
    ['FwYJjwQcGTU094JSNh7ZUFzfXrl1','Enumerator'],
    ['goZMnki9O5P5NSd41CVr8bp9iOx2','Enumerator'],
    ['fwKqNYhmc2MZy0XDT8Pjp1qVrbU2','Enumerator'],
    ['9krdiGYclkcM4h2FQHgA6eQ6CEr1','Enumerator'],
    ['EQP4jeqqThO2MHyfSrZntvooQpP2','Enumerator'],
    ['JDBpuuk7cnX4DxtPgx0UEeMYTii1','Enumerator'],
    ['ssRA4Ew3k6fgZmeoHy4Om2pey3S2','Enumerator'],
    ['a35nWOpXhAc20l9igvbt3MBVkWH3','Enumerator'],
    ['gHNIupXP05QuRQ6C0fvBF5jekTG2','Enumerator'],
    ['IgAgXFVi6OX1BxqKmE4Q2ZW7LNQ2','Enumerator'],
    ['x5XvEpSxr3UHlc19BM0qycmFhYD3','Enumerator'],
    ['MobWS8Qn29h88aKBg8pGXLe97eP2','Enumerator'],
    ['ByuWTeJs5RWTWSx1jjC2AD7cj483','Enumerator'],
    ['ZeXqzrIuP2TdyefW6uJbWelp1DI3','Enumerator'],
    ['4SHl3xICmwhp62HTjkynrPIlEBv1','Enumerator'],
    ['FloGxULWvyV4xbhz0mzDhKPWI902','Enumerator'],
    ['uh6bw32rlNQ2ZskDCJhM0iZrd8p1','Enumerator'],
    ['DGmLngKCIwd7KILLTjAwrScWvOA2','Enumerator'],
    ['mzslJivINYVBswLVZh2agFZNj852','Enumerator'],
    ['GF3ZdoRSU8VA0bZnTQDjk6XkY9w2','Field Coordinator'],
    ['Hl8Wa0kB4PM6RXf5v5fqL4TERhW2','Enumerator'],
    ['cD6uqYezKCZikw7rcl4UI5Bs3px1','Transcriber'],
    ['KWPYV39EjoeuVkMXRnFQ9JhDgF02','Enumerator'],
    ['KgQiCbrOyje6wXVbNnTz4lBD2e43','Enumerator'],
    ['H7eBONDqUvSBONM4UM91P2rXE8B2','Enumerator'],
    ['PciY4C9I8BgVyikEVgi320f2NvQ2','Enumerator'],
    ['ZDrYrtQE2WWGf2sYQMVRA5z9dRo2','Enumerator'],
    ['jDVwdrmSUfMK37IIu7U4qTLbZU23','Enumerator'],
    ['TCNmHrca22b0ZRxyleYd0DVQrSG2','Enumerator'],
    ['B6NNflAultX163gBPobPpa2PU4O2','Enumerator'],
    ['GdAnUkFTpQZz8eKyW3HCfP2JJNd2','Enumerator'],
    ['lFZKHfw7rKcm9fGtsrLh6pk06Bv1','Enumerator'],
    ['a3uw5AXwzNWdisFwjXfZ6Vrjn1B2','Enumerator'],
    ['Vl1xKJbz0xeTcxwLnetiV34qGSB2','Enumerator'],
    ['GJZ3YLSuy4akaLprWfcZTw6pFMj1','Enumerator'],
    ['GhdwiDjY3bPewYkjRfvCRrmUBhb2','Enumerator'],
    ['goBMQbpASXPuHlmuMCFKdb0MvHv2','Transcriber'],
    ['aemEMLeeFiM0RESjGUwK8V2X65v2','Enumerator'],
    ['BS218fQiLKdgu0ECgGDJ4nSIUe53','Translator'],
    ['mAXPSA9d2ngAwlL13r2U8aVYAGt1','Enumerator'],
    ['N6T0jJA4rGYXJ7PzFzSxsSxdn7F3','Enumerator'],
    ['zdFCVEZS4EcVG5fYcodCMbCIGps1','Enumerator'],
    ['Kb2FvU3nE1Vy7NQUVb1XbOuObm53','Enumerator'],
    ['idE49l46qJUZPMrgjjVurYmrHGk1','Enumerator'],
    ['8SDzO28h2jRzwUCdFDJBOXhgnw03','Transcriber'],
    ['1F2ZnwvfHYXE37SxUt1m0VYepto2','Enumerator'],
    ['FZJSkC1SNgg8p59kd7JWjnWonAH3','Enumerator'],
    ['XRtMWYwOKIZFKemHhQelxdktWCX2','Enumerator'],
    ['8GFAUjaFGHNSZcDzxfK5dJdFkWi1','Enumerator'],
    ['JOnonfdTsafc8q1Vy0AD0vhK1bi1','Enumerator'],
    ['M2i4pfLVICQvi78ZGPoUhg2oYO92','Enumerator'],
    ['8G9NRLeiega3axoS1fSFDPWZhWT2','Enumerator'],
    ['9tKsUQEmmmX9PVJBVEAxI73G2ui2','Enumerator'],
    ['M68Lvg4bJtWfiPe86uY250TZGmk1','Enumerator'],
    ['qBkPiplv19UBtZ54SvBQH3wLJ852','Enumerator'],
    ['q94gily06qSO4jI3OV821NqXMKn1','Enumerator'],
    ['6goEQy56FiYIzGyhzfuKb9LaXnM2','Enumerator'],
    ['wniKeXKindNQfotodT2i1nPEqxe2','Enumerator'],
    ['YTEhcoLbC6YXSwRpsQPopo8PXiU2','Enumerator'],
    ['Kb4sYR6wyYQeF2eXMmq3MFKaSoG2','Enumerator'],
    ['Bw04mKRZ0wRWL0GWqySoOyKqrVu1','Enumerator'],
    ['qsf7WPrn0ag0AuYgExuJKxXixO33','Enumerator'],
    ['sNStkIBIY5TrpxXaQFiZTlMfLuB2','Enumerator'],
    ['bDaonuleKvSkh9ydLYP4poyHNSi2','Enumerator'],
    ['odqbJSZkbtZplCW1c4xdKxuopzR2','Enumerator'],
    ['Ew5qt1u4I9ZYCEmj3ud2OfDi4AJ2','Enumerator'],
    ['wqBN8iibouaF6mv4VgWATJisF5f1','Enumerator'],
    ['GarJ8P3oQmXSSxCUCvVPSN3KmYW2','Enumerator'],
    ['CA6XqLcy1nep4ZxrOzoHlHW16a42','Enumerator'],
    ['sKBi6G5IjnQ2ePQqwJBOglql0uM2','Enumerator'],
    ['uVfrMgUy3OOtqz1vZIsFzy5wrgM2','Enumerator'],
    ['4tGKmDzfyYUhaO60MQkoxOlZOsb2','Enumerator'],
    ['rcZpNDFNl0TqolpHrZUKy6VJeqB2','Translator'],
    ['a9GjWuZxMqeo2ZlHa8De9h7mCXr1','Translator'],
    ['GsAqMe9HXHgxeRdBvjL5bijiEPo1','Enumerator'],
    ['LNWkv0PZv1Mko2MHpOoPRYnlnt82','Enumerator'],
    ['al3GIRX6E9dJmGhidfz8LawqGN62','Translator'],
    ['3OQ5JRjmzAXbHXkftkgBb7LqJAY2','Enumerator'],
    ['hFcZXvafSiZgvG4yqjUJvprVXx62','Enumerator'],
    ['Y3G5FgnAxyLhTDeLKSSyNFmfA3m2','Enumerator'],
    ['5Ct3jmoteXPTjBham0frYEVlA493','Enumerator'],
    ['ljY63fPr1FeBxjsIrUnv1IZLEME3','Enumerator'],
    ['lXzXox0ACSV1QgDuhEcHKfevWwp1','Enumerator'],
    ['cLpix3nNF7fsNDinpIKsywosBeq1','Enumerator'],
    ['KWo0LaCp9vWrSf1Xtr8ubjUhXMk2','Enumerator'],
    ['CuKDTMIDrqh4bRNi89RR7vELCNq2','Enumerator'],
    ['SK14YzyNM0WZy2YOGUwrUzhTEZQ2','Enumerator'],
    ['Nn3JLUZDa0SaKppm5dWjy1FbrRx2','Translator'],
    ['QZ2AKqR0LwhEzJxue6jOJ6bygyF2','Transcriber'],
    ['kTnnfnScKIdKzT1O4XMKqtMXv3K3','Enumerator'],
    ['1jI7keHXXGhME9Z7qWAjmqOoI2u1','Enumerator'],
    ['yFXxk0hX45hu7wbJSQguGFvI9QD3','Enumerator'],
    ['SvrBf6J9hsaPgjTkaHf8364KUMm2','Enumerator'],
    ['4F4bf2P2fVgz1XdBO06IGsbMsph1','Field Coordinator'],
    ['vS6BuS2FLiSVRjm5LxnoU2ITacO2','Enumerator'],
    ['cbqX2qIz5IPcRNcSPIv4PYsoif52','Enumerator'],
    ['Z4mY36u1WWUXHhUWc5QxjCoYrWy1','Enumerator'],
    ['kKbr50lFpXcaEiJibPAMMuxmaGg2','Enumerator'],
    ['Pu9PHaKpa6Qhr5y4TZUSj56Xy0o1','Enumerator'],
    ['a8MiByxng5Qd6rzWZjX0VVtl2Za2','Field Coordinator'],
    ['IntTNvK2U8fQ9nrDoavN5mBio962','Enumerator'],
    ['i8v6cnJSyHbpHDdPbujzfpXzX8B3','Enumerator'],
    ['h8af7W6qXqVZ3U4nsxiO9SIx4Mn2','Enumerator'],
    ['K4Vhaq3z4yU2BhrNsLeBrRE6lSx1','Enumerator'],
    ['sEUpdS9MN6XSgYlF188zMxOeve53','Enumerator'],
    ['ThLliMbGpWTMbeZ9FkgzdmtfzPH3','Enumerator'],
    ['4NdGYNShG1MIAXKwzujXBsebv6s2','Enumerator'],
    ['cRrD1XOsVPTMPETcJ3ZgaDXwWkd2','Enumerator'],
    ['TecaSOOPycYPo1hZ3CPaNWT8qOk2','Enumerator'],
    ['jqZkxCkrMxUYvAZEGvAPAqD0IVx1','Enumerator'],
    ['tYvWevsWk2VlSot9rQ8RjjVDBHO2','Enumerator'],
    ['SF5GTBb2OoZ8REFE7fh2deIWjek2','Enumerator'],
    ['QlMGpgU0sKbZqpr30VjYdP5AtA42','Enumerator'],
    ['xVtFrFd36Bd3lmczVe9eqEAwOBk2','Transcriber'],
    ['HQopv1BuO8NbOQ4SB9C0eGjBbHY2','Enumerator'],
    ['T6HfbHFS5pSzHgjZK7wvVtQvuwE3','Enumerator'],
    ['hXW97CLtcSZNVoRVLucssHNq1oo2','Translator'],
    ['SvjoasxkhDNprQKzGHdJggO74pq1','Enumerator'],
    ['ILViICD7wjbd2OYkbFpyZFQqFNo1','Enumerator'],
    ['gJ5aKF3cj8Xy3V6g4Y1Zsz9sTHA3','Field Coordinator'],
    ['fX35ZGfJgWTp9vvw8StkXrcdao83','Translator'],
    ['UkuHfGAJSUQ7u1Zi5uX9eaYfV3p1','Enumerator'],
    ['tDNDnvrM38TMfcybEQIqgenr1KP2','Enumerator'],
    ['JLpMjOI4KWSi8zjap6WgL00fjED2','Field Coordinator'],
    ['HpqZ9xAR1mUfNmQpDgh60ajACsf2','Enumerator'],
    ['Ihy026q0pmWXY1ecqdiJB6YxbvD2','Enumerator'],
    ['p5rhpJKhPvYJKTViS6EtIqWYIIb2','Enumerator'],
    ['hCtoNjjKJZXwBxatCWBdWEGh5D02','Enumerator'],
    ['kgZlQ8qwPogPkPLhJVGqIvJzBIj1','Translator'],
    ['XXDLWCHhD9SOM7PejMruWbMMsAS2','Enumerator'],
    ['PVjBSVxGndanGoZ1EWsqZvWOcAc2','Enumerator'],
    ['xb4UIQ9AnjakVCP5IPwdgXhAyjw2','Enumerator'],
    ['vXjHSL6ttuVw6AW81hjt4kuqofH3','Enumerator'],
    ['mCPXkiado7a5haOSzQIrGrB9Plz2','Enumerator'],
  ];

  static const List<String> users2 = [
    'diane.ingabirehirwa@laterite.com',
    'francois.imanayumvabayo@laterite.com',
    'yvette.amahoro@laterite.com',
    'scholas.buranga@laterite.com',
    'jeannette.mireilleiradukunda@laterite.com',
    'jimmy.ruhanga@laterite.com',
    'leonille.mutambarungu@laterite.com',
    'camarade.samuelamerika@laterite.com',
    'herve.nyirimihigo@laterite.com',
    'emma.roseuwimana@laterite.com',
    'pacifique.kwizera@laterite.com',
    'nadine.tuyishime@laterite.com',
    'theophile.nyirimana@laterite.com',
    'elie.mandela@laterite.com',
    'rosine.nishimwe@laterite.com',
    'assuman.muhire@laterite.com',
    'fidele.maniraguha@laterite.com',
    'nadine.jessicaumuhoza@laterite.com',
    'leon.habineza@laterite.com',
    'sophie.akimana@laterite.com',
    'clemence.nduwayo@laterite.com',
    'juliet.tusingirwe@laterite.com',
    'morris.kayitare@laterite.com',
    'jean.claudeturatsinze@laterite.com',
    'anitha.uwingabiye@laterite.com',
    'marie.chantalmukantwali@laterite.com',
    'patrick.tuyisenge@laterite.com',
    'anne.niyomubyeyi@laterite.com',
    'grace.uwase@laterite.com',
    'consolee.bagwaneza@laterite.com',
    'manasse.twagiramungu@laterite.com',
    'emeline.hategekimana@laterite.com',
    'dieudonne.tuyisabyimbabazi@laterite.com',
    'therese.uwamahoro@laterite.com',
    'patient.nshongore@laterite.com',
    'martin.hubertikuramutse@laterite.com',
    'jean.claudenshimiyimana@laterite.com',
    'jean.bosconsengiyumva@laterite.com',
    'elisee.dushimimana@laterite.com',
    'john.nshaija@laterite.com',
    'jacqueline.bamurange@laterite.com',
    'petrine.muhoza@laterite.com',
    'james.nkuranga@laterite.com',
    'eric.ntakirutimana@laterite.com',
    'christophe.rukundo@laterite.com',
    'fabiola.bagorora@laterite.com',
    'sixbert.shema@laterite.com',
    'marie.assoumptaumuhoza@laterite.com',
    'christian.nkubito@laterite.com',
    'jean.baptistenyaminani@laterite.com',
    'rebecca.tuganeyesu@laterite.com',
    'sylvia.ingabire@laterite.com',
    'grace.nyiramatungo@laterite.com',
    'hamdoun.twagirimana@laterite.com',
    'theobald.nshimiyimana@laterite.com',
    'theodomir.ntasoni@laterite.com',
    'rodrigue.bukozi@laterite.com',
    'anne.mukarebero@laterite.com',
    'egidie.nirere@laterite.com',
    'solange.dusabiyera@laterite.com',
    'sandrine.uwiduhaye@laterite.com',
    'jean.paulishimwe@laterite.com',
    'yvette.umwali@laterite.com',
    'florence.niyigena@laterite.com',
    'betty.mukankusi@laterite.com',
    'emylie.gahimbare@laterite.com',
    'samantha.mugabe@laterite.com',
    'gloria.igiraneza@laterite.com',
    'rosalie.mukeshimana@laterite.com',
    'tresor.kambanda@laterite.com',
    'sandrine.uwamahoro@laterite.com',
    'alice.benihirwe@laterite.com',
    'thamar.gatesi@laterite.com',
    'rosine.uwamariya@laterite.com',
    'sonia.angerugwiro@laterite.com',
    'clarisse.mukandindacyuzuzo@laterite.com',
    'euphrosine.mukankebukande@laterite.com',
    'aloys.ishimwe@laterite.com',
    'emmanuel.musanganya@laterite.com',
    'orly.mugwaneza@laterite.com',
    'irma.girimbabazi@laterite.com',
    'joseph.elvinkatete@laterite.com',
    'jessica.irambona@laterite.com',
    'jeanine.nyiramana@laterite.com',
    'joseph.nsengimana@laterite.com',
    'patricia.ingabire@laterite.com',
    'etienne.musemakweli@laterite.com',
    'claudien.rudasingwa@laterite.com',
    'pauline.kezakimana@laterite.com',
    'peter.muvunyi@laterite.com',
    'olivier.duhoranimana@laterite.com',
    'vedaste.nizeyimana@laterite.com',
    'private.dukundimana@laterite.com',
    'raissa.mugisha@laterite.com',
    'muhodari.kadugano@laterite.com',
    'fraterne.mutimanama@laterite.com',
    'perpetue.dusabimana@laterite.com',
    'raissa.kamaliza@laterite.com',
    'rosine.uwantege@laterite.com',
    'arlette.saroniyibizi@laterite.com',
    'daniella.ujeneza@laterite.com',
    'albin.shema@laterite.com',
    'thomas.byiringiro@laterite.com',
    'sam.kagwisagye@laterite.com',
    'elias.kagabo@laterite.com',
    'didier.usanase@laterite.com',
    'clarisse.gahunzireuwitonze@laterite.com',
    'olive.tuyishimire@laterite.com',
    'lyvine.umutoni@laterite.com',
    'noel.olivieringabire@laterite.com',
    'gisele.mwizerwa@laterite.com',
    'joseph.manzi@laterite.com',
    'jackline.mugoboka@laterite.com',
    'philbert.ishimwe@laterite.com',
    'bernard.nshimiyimana@laterite.com',
    'delphine.abijuru@laterite.com',
    'marie.aimeenakure@laterite.com',
    'jean.baptistekwizera@laterite.com',
    'diane.karire@laterite.com',
    'beatrice.safikalumbi@laterite.com',
    'jean.dedieuntivuguruzwa@laterite.com',
    'moise.bonheur@laterite.com',
    'marius.munezero@laterite.com',
    'julius.ntaganda@laterite.com',
    'juliet.elisagiraso@laterite.com',
    'agnes.muhawenimana@laterite.com',
    'aline.kenzangirankugire@laterite.com',
    'belinda.ingabire@laterite.com',
    'clement.rugira@laterite.com',
    'sarah.uwineza@laterite.com',
    'honoré.ndayishimye@laterite.com',
    'jean.paulrugwiro@laterite.com',
    'honorine.uwera@laterite.com',
    'sarah.kamikazi@laterite.com',
    'clementine.nyirarukundo@laterite.com',
    'janecie.rangiraumutoni@laterite.com',
    'serge.priamnsanzineza@laterite.com',
    'appolinaire.twagiramungu@laterite.com',
    'serapie.hakizimana@laterite.com',
    'fabrice.birasa@laterite.com',
    'vestine.masengesho@laterite.com',
    'diane.mukabagorora@laterite.com',
    'ally.mugabukenukwe@laterite.com',
    'esther.nsimirelulando@laterite.com',
    'donatha.mugirase@laterite.com',
    'philomene.nyirarukundo@laterite.com',
    'clarisse.kamanziakagera@laterite.com',
    'jeannette.batamuliza@laterite.com',
    'felicien.irafasha@laterite.com',
    'janvier.bananezakayitare@laterite.com',
    'cedric.kigenzamugabo@laterite.com',
    'ines.michelleiradukunda@laterite.com',
    'jean.francoisnyamuniga@laterite.com',
    'adeline.tuyizeregasinzigwa@laterite.com',
    'grace.dusabe@laterite.com',
    'jean.dedieudusenge@laterite.com',
    'charlotte.uwimana@laterite.com',
    'billy.michelmigambi@laterite.com',
    'damien.munyandekwe@laterite.com',
    'marie.louiseniragire@laterite.com',
    'francoise.uwanyirigira@laterite.com',
    'marie.clairegihozo@laterite.com',
    'benjamin.abijuru@laterite.com',
    'francine.uwamahoro@laterite.com',
    'samson.gatera@laterite.com',
    'diana.umutoniburamba@laterite.com',
    'joel.shumbusho@laterite.com',
    'alphonsine.uwantege@laterite.com',
    'jean.damascenetuyizere@laterite.com',
    'brenda.mutoni@laterite.com',
    'quintia.iradukunda@laterite.com',
    'cansilde.ingabire@laterite.com',
    'michel.ndayishimiye@laterite.com',
    'marie.gracemuhimpundu@laterite.com',
    'nicole.beza@laterite.com',
    'aimable.nsengiyumva@laterite.com',
    'jean.damascenentakirutimana@laterite.com',
    'audace.nakeshimana@laterite.com',
    'allen.ingabire@laterite.com',
    'agnes.bamurange@laterite.com',
    'aisha.umutesi@laterite.com',
    'dina.marcellaabeneto@laterite.com',
    'hassan.karekezi@laterite.com',
    'lambert.habimana@laterite.com',
    'desire.ngurusu@laterite.com',
    'felix.mucyo@laterite.com',
    'simplice.ihirwe@laterite.com',
    'jeanne.francoisemukabarezi@laterite.com',
    'perfect.mfashijwenimana@laterite.com',
    'emmanuel.uwayezu@laterite.com',
    'patrick.ndayambaje@laterite.com',
    'richard.ngirumuremyi@laterite.com',
    'didier.girumuturanyi@laterite.com',
    'blandine.nirere@laterite.com',
    'jeanne.uwimana@laterite.com',
    'sabin.sheja@laterite.com',
    'aime.bienfaitigiraneza@laterite.com',
    'pascaline.mugiranezamunezero@laterite.com',
    'thierry.ndezemaniragaba@laterite.com',
    'ruth.fionabayimenye@laterite.com',
    'theodosie.uwitonze@laterite.com',
    'micheline.kwizera@laterite.com',
    'claudette.igiraneza@laterite.com',
    'theophile.kalisa@laterite.com',
    'silas.gasasira@laterite.com',
    'laetitia.uwera@laterite.com',
    'aulique.bereniceiguhozesindikubwabo@laterite.com',
    'christian.ndaruhuye@laterite.com',
    'obed.nahayo@laterite.com',
    'blandine.uwera@laterite.com',
    'alain.christianruzindana@laterite.com',
    'alain.mwizerwa@laterite.com',
    'emerance.iragena@laterite.com',
    'malik.martialmanziruzindaza@laterite.com',
    'odette.nishimwe@laterite.com',
    'didier.gashema@laterite.com',
    'aline.uwineza@laterite.com',
    'ange.sybillesingiza@laterite.com',
    'norette.ingabire@laterite.com',
    'pamela.rudahunga@laterite.com',
    'pamela.marieclaudemizero@laterite.com',
    'marie.nellyadelineuwayezu@laterite.com',
    'erick.joseph@laterite.com',
  ];
  static const List<List<String>> users = [
    ['josee.uwayezu', 'Enumerator'],
    ['innocent.mushamuka', 'Enumerator'],
    ['diane.ingabirehirwa', 'Enumerator'],
    ['esperance.uwitonze', 'Enumerator'],
    ['nadege.umurutasate', 'Transcriber'],
    ['eric.karama', 'Enumerator'],
    ['flavia.kantengwa', 'Field Coordinator'],
    ['olivier.pacifiqueniyomugabo', 'Enumerator'],
    ['blaise.musabe', 'Enumerator'],
    ['aloysie.niyoyita', 'Enumerator'],
    ['juliet.nyirasafari', 'Enumerator'],
    ['protais.nkundineza', 'Enumerator'],
    ['bernard.uwayisaba', 'Field Coordinator'],
    ['evariste.nizeyimana', 'Enumerator'],
    ['bernard.nkurunziza', 'Enumerator'],
    ['clarisse.mukundwa', 'Translator'],
    ['olivier.mutabazi', 'Enumerator'],
    ['charles.mwizerwa', 'Enumerator'],
    ['claire.akamanzikaneza', 'Enumerator'],
    ['carine.kalinda', 'Enumerator'],
    ['jean.dedieuuwihaye', 'Enumerator'],
    ['blandine.umuziranenge', 'Enumerator'],
    ['geoffrey.mugisha', 'Enumerator'],
    ['sonia.hirwa', 'Enumerator'],
    ['annick.izabayo', 'Enumerator'],
    ['ariane.merciisimbi', 'Enumerator'],
    ['egide.sakindi', 'Enumerator'],
    ['florence.sumwiza', 'Enumerator'],
    ['hyacinthe.kakuze', 'Enumerator'],
    ['redempta.ingabire', 'Field Supervisor'],
    ['joseph.uwimana', 'Enumerator'],
    ['vital.habimana', 'Enumerator'],
    ['pie.nkubito', 'Enumerator'],
    ['denis.karenzi', 'Enumerator'],
    ['jean.boscohakizimana', 'Enumerator'],
    ['angelo.igitego', 'Translator'],
    ['denise.murinzi', 'Enumerator'],
    ['francine.irankunda', 'Enumerator'],
    ['francoise.uwineza', 'Enumerator'],
    ['betty.nyirahabimana', 'Enumerator'],
    ['joyce.rulinda', 'Enumerator'],
    ['francois.imanayumvabayo', 'Enumerator'],
    ['chantal.kabatesi', 'Enumerator'],
    ['yvette.uwamariya', 'Enumerator'],
    ['afrika.prudencehabinshuti', 'Enumerator'],
    ['clementine.mukagatare', 'Enumerator'],
    ['claude.mudahemuka', 'Enumerator'],
    ['yvette.amahoro', 'Field Coordinator'],
    ['gustave.niringire', 'Enumerator'],
    ['francoise.uwiringiyingabire', 'Enumerator'],
    ['jean.paulniyibizi', 'Enumerator'],
    ['fabienne.mutamuriza', 'Enumerator'],
    ['angelique.kwizera', 'Enumerator'],
    ['pauline.kimenyi', 'Enumerator'],
    ['kellia.umulisa', 'Enumerator'],
    ['alice.nibakure', 'Enumerator'],
    ['bertrand.rutagarama', 'Translator'],
    ['alexis.gisore', 'Enumerator'],
    ['leontine.byukusenge', 'Enumerator'],
    ['jackson.ngiruwonsanga', 'Enumerator'],
    ['olivier.mutijimana', 'Enumerator'],
    ['anitha.uwasesendakize', 'Enumerator'],
    ['pascal.habineza', 'Translator'],
    ['jean.claudendayiragije', 'Enumerator'],
    ['amandine.karire', 'Enumerator'],
    ['scholas.buranga', 'Enumerator'],
    ['alliyah.kaneza', 'Enumerator'],
    ['abdou.kamanzi', 'Enumerator'],
    ['clemence.tuyishimire', 'Enumerator'],
    ['honoree.victoiremukashema', 'Enumerator'],
    ['alice.nibagirwe', 'Enumerator'],
    ['henry.markrugaba', 'Enumerator'],
    ['marie.aimeeuwera', 'Enumerator'],
    ['hyacinthe.mushimiyimana', 'Enumerator'],
    ['ingabire.dianehirwa', 'Enumerator'],
    ['francois.regisniringiyimana', 'Enumerator'],
    ['alice.neza', 'Enumerator'],
    ['sharon.uwineza', 'Enumerator'],
    ['gloriose.ingabire', 'Field Coordinator'],
    ['sonia.umutoniwase', 'Enumerator'],
    ['susan.teta', 'Translator'],
    ['norah.natukunda', 'Enumerator'],
    ['ben.dedalesixtehigiro', 'Enumerator'],
    ['emmanuel.twagirayezu', 'Enumerator'],
    ['evariste.nyirimanzi', 'Enumerator'],
    ['clarisse.uwase', 'Enumerator'],
    ['jean.paulhabimana', 'Enumerator'],
    ['christian.shema', 'Enumerator'],
    ['angelique.ingabire', 'Enumerator'],
    ['bernice.iradukunda', 'Enumerator'],
    ['flora.umulisa', 'Enumerator'],
    ['etienne.babuzindunduro', 'Enumerator'],
    ['leatitia.mukeshimana', 'Enumerator'],
    ['anicet.nsengumuremyi', 'Enumerator'],
    ['evelyne.mutuyimana', 'Enumerator'],
    ['octave.vuguziga', 'Enumerator'],
    ['liliose.umutesi', 'Enumerator'],
    ['clarisse.impano', 'Enumerator'],
    ['eric.rurinda', 'Enumerator'],
    ['alice.uwera', 'Translator'],
    ['toute.chantalumwiza', 'Enumerator'],
    ['narcisse.mutanguha', 'Enumerator'],
    ['tharcisse.bizimana', 'Enumerator'],
    ['godfrey.mutsinzi', 'Enumerator'],
    ['eric.gasana', 'Enumerator'],
    ['emmanuel.twagirimana', 'Enumerator'],
    ['magalie.ntahokaja', 'Translator'],
    ['donatien.majyambere', 'Enumerator'],
    ['emmanuel.brunondayisenga', 'Enumerator'],
    ['marie.auroreniyitangamanzi', 'Transcriber'],
    ['solange.uwingeri', 'Enumerator'],
    ['divine.nikuze', 'Field Coordinator'],
    ['adrien.gakumbahabimana', 'Enumerator'],
    ['rhona.tumushabe', 'Enumerator'],
    ['diane.ishimwe', 'Enumerator'],
    ['benjamin.cyuzuzo', 'Enumerator'],
    ['geraldine.mukantabana', 'Enumerator'],
    ['christelle.uwimana', 'Enumerator'],
    ['shakila.umutonikamatali', 'Translator'],
    ['jean.baptisteiradukunda', 'Enumerator'],
    ['jean.ntawanguwe', 'Transcriber'],
    ['emmy.kangwege', 'Enumerator'],
    ['gaspard.nzasabimfura', 'Transcriber'],
    ['rachel.cyuzuzo', 'Transcriber'],
    ['lucie.dusengiyaremye', 'Field Supervisor'],
    ['anita.mamenero', 'Enumerator'],
    ['philbert.muhire', 'Enumerator'],
    ['billy.gilberthabimanacyusa', 'Translator'],
    ['david.ndayisenga', 'Enumerator'],
    ['dorcyne.nishimwe', 'Enumerator'],
    ['barbara.umuhoza', 'Translator'],
    ['josiane.nishimwe', 'Enumerator'],
    ['fortunee.umuhozawase', 'Enumerator'],
    ['ntegana.musirimu', 'Enumerator'],
    ['aline.mukakayumba', 'Enumerator'],
    ['patrice.nshuti', 'Enumerator'],
    ['deogratias.nshimiyimana', 'Enumerator'],
    ['violet.kagabirwa', 'Enumerator'],
    ['nshuti.samantha', 'Enumerator'],
    ['dorothee.karehe', 'Enumerator'],
    ['marie.claudineumubyeyi', 'Enumerator'],
    ['jeannette.mireilleiradukunda', 'Enumerator'],
    ['jimmy.ruhanga', 'Enumerator'],
    ['leonille.mutambarungu', 'Enumerator'],
    ['camarade.samuelamerika', 'Enumerator'],
    ['charlene.kanyange', 'Enumerator'],
    ['herve.nyirimihigo', 'Enumerator'],
    ['emma.roseuwimana', 'Enumerator'],
    ['pacifique.kwizera', 'Enumerator'],
    ['immaculee.nyirandizihiwe', 'Enumerator'],
    ['nadine.tuyishime', 'Enumerator'],
    ['valentine.mutamulizambayiha', 'Enumerator'],
    ['theophile.nyirimana', 'Enumerator'],
    ['elie.mandela', 'Translator'],
    ['rosine.nishimwe', 'Enumerator'],
    ['assuman.muhire', 'Enumerator'],
    ['fidele.maniraguha', 'Enumerator'],
    ['nadine.jessicaumuhoza', 'Enumerator'],
    ['leon.habineza', 'Enumerator'],
    ['sophie.akimana', 'Enumerator'],
    ['clemence.nduwayo', 'Enumerator'],
    ['juliet.tusingirwe', 'Enumerator'],
    ['morris.kayitare', 'Translator'],
    ['jean.claudeturatsinze', 'Enumerator'],
    ['marcel.hagenashema', 'Enumerator'],
    ['anitha.uwingabiye', 'Enumerator'],
    ['marie.chantalmukantwali', 'Enumerator'],
    ['patrick.tuyisenge', 'Enumerator'],
    ['angelique.muhawenimana', 'Enumerator'],
    ['anne.niyomubyeyi', 'Enumerator'],
    ['mireille.umutonisekamana', 'Transcriber'],
    ['grace.uwase', 'Translator'],
    ['consolee.bagwaneza', 'Enumerator'],
    ['noel.ndamukunda', 'Enumerator'],
    ['manasse.twagiramungu', 'Field Coordinator'],
    ['emeline.hategekimana', 'Field Coordinator'],
    ['yvette.umugiraneza', 'Enumerator'],
    ['dieudonne.tuyisabyimbabazi', 'Enumerator'],
    ['therese.uwamahoro', 'Translator'],
    ['patient.nshongore', 'Enumerator'],
    ['christian.kayonga', 'Enumerator'],
    ['denise.kayitesingamije', 'Enumerator'],
    ['xavier.nyandwi', 'Enumerator'],
    ['martin.hubertikuramutse', 'Enumerator'],
    ['jean.claudenshimiyimana', 'Enumerator'],
    ['jean.bosconsengiyumva', 'Enumerator'],
    ['elisee.dushimimana', 'Enumerator'],
    ['john.nshaija', 'Enumerator'],
    ['christian.muhire', 'Enumerator'],
    ['jacqueline.bamurange', 'Enumerator'],
    ['vanessa.ingabire', 'Enumerator'],
    ['petrine.muhoza', 'Enumerator'],
    ['james.nkuranga', 'Enumerator'],
    ['eric.ntakirutimana', 'Enumerator'],
    ['christophe.rukundo', 'Enumerator'],
    ['clarisse.kazayirwa', 'Enumerator'],
    ['fabiola.bagorora', 'Enumerator'],
    ['christine.nyirandikumana', 'Enumerator'],
    ['sixbert.shema', 'Enumerator'],
    ['marie.assoumptaumuhoza', 'Enumerator'],
    ['christian.nkubito', 'Enumerator'],
    ['jean.baptistenyaminani', 'Enumerator'],
    ['pie.celestinhakizimana', 'Enumerator'],
    ['rebecca.tuganeyesu', 'Enumerator'],
    ['sylvia.ingabire', 'Enumerator'],
    ['grace.nyiramatungo', 'Enumerator'],
    ['grace.umuganwa', 'Enumerator'],
    ['charles.hitimana', 'Enumerator'],
    ['hamdoun.twagirimana', 'Enumerator'],
    ['joyce.munezero', 'Field Coordinator'],
    ['theobald.nshimiyimana', 'Enumerator'],
    ['theodomir.ntasoni', 'Enumerator'],
    ['rodrigue.bukozi', 'Enumerator'],
    ['irene.nteziryayo', 'Enumerator'],
    ['anne.mukarebero', 'Enumerator'],
    ['egidie.nirere', 'Enumerator'],
    ['solange.dusabiyera', 'Enumerator'],
    ['sandrine.uwiduhaye', 'Enumerator'],
    ['jean.paulishimwe', 'Enumerator'],
    ['joseph.murinzi', 'Enumerator'],
    ['yvette.umwali', 'Enumerator'],
    ['florence.niyigena', 'Enumerator'],
    ['salwa.uwabasindi', 'Enumerator'],
    ['betty.mukankusi', 'Enumerator'],
    ['emylie.gahimbare', 'Enumerator'],
    ['samantha.mugabe', 'Enumerator'],
    ['stella.mukakalisa', 'Enumerator'],
    ['gloria.igiraneza', 'Enumerator'],
    ['rosalie.mukeshimana', 'Enumerator'],
    ['tresor.kambanda', 'Translator'],
    ['faith.mutesi', 'Enumerator'],
    ['sandrine.uwamahoro', 'Enumerator'],
    ['alice.benihirwe', 'Enumerator'],
    ['thamar.gatesi', 'Enumerator'],
    ['rosine.uwamariya', 'Enumerator'],
    ['valentine.nishimwe', 'Enumerator'],
    ['geoffrey.karara', 'Enumerator'],
    ['sonia.angerugwiro', 'Transcriber'],
    ['clarisse.mukandindacyuzuzo', 'Enumerator'],
    ['euphrosine.mukankebukande', 'Enumerator'],
    ['aloys.ishimwe', 'Enumerator'],
    ['emmanuel.musanganya', 'Enumerator'],
    ['orly.mugwaneza', 'Enumerator'],
    ['irma.girimbabazi', 'Enumerator'],
    ['joseph.elvinkatete', 'Enumerator'],
    ['jessica.irambona', 'Enumerator'],
    ['jeanine.nyiramana', 'Enumerator'],
    ['yvette.abijuru', 'Transcriber'],
    ['fred.kaberuka', 'Enumerator'],
    ['joseph.nsengimana', 'Enumerator'],
    ['jonas.niyogakiza', 'Enumerator'],
    ['patricia.ingabire', 'Enumerator'],
    ['etienne.musemakweli', 'Field Coordinator'],
    ['claudien.rudasingwa', 'Enumerator'],
    ['pauline.kezakimana', 'Enumerator'],
    ['octave.gakunzi', 'Enumerator'],
    ['peter.muvunyi', 'Enumerator'],
    ['yves.fabienkarasira', 'Enumerator'],
    ['olivier.duhoranimana', 'Enumerator'],
    ['vedaste.nizeyimana', 'Enumerator'],
    ['private.dukundimana', 'Enumerator'],
    ['sylvie.karemera', 'Enumerator'],
    ['raissa.mugisha', 'Translator'],
    ['muhodari.kadugano', 'Enumerator'],
    ['fraterne.mutimanama', 'Enumerator'],
    ['perpetue.dusabimana', 'Enumerator'],
    ['raissa.kamaliza', 'Translator'],
    ['rosine.uwantege', 'Field Coordinator'],
    ['arlette.saroniyibizi', 'Enumerator'],
    ['daniella.ujeneza', 'Translator'],
    ['albin.shema', 'Enumerator'],
    ['thomas.byiringiro', 'Enumerator'],
    ['sam.kagwisagye', 'Enumerator'],
    ['christian.rwabununga', 'Enumerator'],
    ['elias.kagabo', 'Transcriber'],
    ['didier.usanase', 'Enumerator'],
    ['clarisse.gahunzireuwitonze', 'Enumerator'],
    ['olive.tuyishimire', 'Transcriber'],
    ['lyvine.umutoni', 'Enumerator'],
    ['noel.olivieringabire', 'Enumerator'],
    ['eric.kirezi', 'Field Supervisor'],
    ['liliose.mukeshimana', 'Enumerator'],
    ['gisele.mwizerwa', 'Enumerator'],
    ['joseph.manzi', 'Enumerator'],
    ['constantin.bihoyiki', 'Enumerator'],
    ['dominique.ntwari', 'Enumerator'],
    ['jackline.mugoboka', 'Enumerator'],
    ['jean.felixkayiranga', 'Enumerator'],
    ['philbert.ishimwe', 'Enumerator'],
    ['celine.mukantwali', 'Enumerator'],
    ['jean.dedieudushimimana', 'Enumerator'],
    ['bernard.nshimiyimana', 'Enumerator'],
    ['delphine.abijuru', 'Enumerator'],
    ['marie.aimeenakure', 'Enumerator'],
    ['assumpta.cyuzuzo', 'Enumerator'],
    ['jean.baptistekwizera', 'Translator'],
    ['diane.karire', 'Enumerator'],
    ['beatrice.safikalumbi', 'Enumerator'],
    ['aphrodis.nshizirungu', 'Enumerator'],
    ['jean.dedieuntivuguruzwa', 'Enumerator'],
    ['magnifique.mukundwa', 'Transcriber'],
    ['moise.bonheur', 'Enumerator'],
    ['marius.munezero', 'Enumerator'],
    ['julius.ntaganda', 'Enumerator'],
    ['juliet.elisagiraso', 'Translator'],
    ['agnes.muhawenimana', 'Enumerator'],
    ['aline.kenzangirankugire', 'Enumerator'],
    ['belinda.ingabire', 'Field Coordinator'],
    ['clement.rugira', 'Enumerator'],
    ['diane.clarisseuwibambe', 'Enumerator'],
    ['sarah.uwineza', 'Enumerator'],
    ['honoré.ndayishimye', 'Enumerator'],
    ['dativa.kabatsi', 'Enumerator'],
    ['jean.paulrugwiro', 'Enumerator'],
    ['honorine.uwera', 'Enumerator'],
    ['denys.buhake', 'Enumerator'],
    ['sarah.kamikazi', 'Enumerator'],
    ['clementine.nyirarukundo', 'Enumerator'],
    ['janecie.rangiraumutoni', 'Enumerator'],
    ['serge.priamnsanzineza', 'Transcriber'],
    ['appolinaire.twagiramungu', 'Enumerator'],
    ['serapie.hakizimana', 'Enumerator'],
    ['fabrice.birasa', 'Enumerator'],
    ['vestine.masengesho', 'Enumerator'],
    ['steven.mucyo', 'Translator'],
    ['diane.mukabagorora', 'Enumerator'],
    ['fred.mukunzi', 'Enumerator'],
    ['ally.mugabukenukwe', 'Enumerator'],
    ['esther.nsimirelulando', 'Field Supervisor'],
    ['donatha.mugirase', 'Translator'],
    ['philomene.nyirarukundo', 'Enumerator'],
    ['clarisse.kamanziakagera', 'Translator'],
    ['jeannette.batamuliza', 'Enumerator'],
    ['felicien.irafasha', 'Enumerator'],
    ['janvier.bananezakayitare', 'Qualitative'],
    ['cedric.kigenzamugabo', 'Translator'],
    ['answar.twizerimana', 'Enumerator'],
    ['ines.michelleiradukunda', 'Enumerator'],
    ['jean.francoisnyamuniga', 'Enumerator'],
    ['rene.francissimbimvuyekure', 'Transcriber'],
    ['adeline.tuyizeregasinzigwa', 'Enumerator'],
    ['grace.dusabe', 'Enumerator'],
    ['jean.dedieudusenge', 'Enumerator'],
    ['charlotte.uwimana', 'Transcriber'],
    ['emma.roseumwali', 'Field Coordinator'],
    ['billy.michelmigambi', 'Enumerator'],
    ['damien.munyandekwe', 'Enumerator'],
    ['marie.louiseniragire', 'Enumerator'],
    ['francoise.uwanyirigira', 'Enumerator'],
    ['marie.clairegihozo', 'Enumerator'],
    ['benjamin.abijuru', 'Enumerator'],
    ['francine.uwamahoro', 'Enumerator'],
    ['samson.gatera', 'Enumerator'],
    ['diana.umutoniburamba', 'Enumerator'],
    ['joel.shumbusho', 'Enumerator'],
    ['alphonsine.uwantege', 'Enumerator'],
    ['jean.damascenetuyizere', 'Enumerator'],
    ['brenda.mutoni', 'Enumerator'],
    ['yvette.nyinawamuntu', 'Enumerator'],
    ['quintia.iradukunda', 'Translator'],
    ['cansilde.ingabire', 'Enumerator'],
    ['michel.ndayishimiye', 'Enumerator'],
    ['marie.gracemuhimpundu', 'Enumerator'],
    ['josiane.mukayitesi', 'Enumerator'],
    ['nicole.beza', 'Enumerator'],
    ['aimable.nsengiyumva', 'Enumerator'],
    ['jean.damascenentakirutimana', 'Enumerator'],
    ['frank.karengera', 'Enumerator'],
    ['jean.ericcyizamugabe', 'Enumerator'],
    ['audace.nakeshimana', 'Translator'],
    ['allen.ingabire', 'Translator'],
    ['agnes.bamurange', 'Translator'],
    ['aisha.umutesi', 'Enumerator'],
    ['lucie.tuyishime', 'Enumerator'],
    ['elisabeth.yambabariye', 'Enumerator'],
    ['dina.marcellaabeneto', 'Enumerator'],
    ['hassan.karekezi', 'Enumerator'],
    ['herve.rurangwairadukunda', 'Translator'],
    ['lambert.habimana', 'Enumerator'],
    ['desire.ngurusu', 'Enumerator'],
    ['aime.laurenttwizerimana', 'Translator'],
    ['felix.mucyo', 'Enumerator'],
    ['simplice.ihirwe', 'Enumerator'],
    ['justine.mucyo', 'Enumerator'],
    ['jeanne.francoisemukabarezi', 'Enumerator'],
    ['jean.dedieuuwayezu', 'Enumerator'],
    ['perfect.mfashijwenimana', 'Transcriber'],
    ['emmanuel.uwayezu', 'Enumerator'],
    ['patrick.ndayambaje', 'Field Coordinator'],
    ['richard.ngirumuremyi', 'Enumerator'],
    ['didier.girumuturanyi', 'Enumerator'],
    ['blandine.nirere', 'Enumerator'],
    ['jeanne.uwimana', 'Enumerator'],
    ['norbert.kwizera', 'Enumerator'],
    ['sabin.sheja', 'Enumerator'],
    ['aime.bienfaitigiraneza', 'Translator'],
    ['pascaline.mugiranezamunezero', 'Transcriber'],
    ['thierry.ndezemaniragaba', 'Enumerator'],
    ['ruth.fionabayimenye', 'Enumerator'],
    ['theodosie.uwitonze', 'Enumerator'],
    ['richard.basanase', 'Enumerator'],
    ['micheline.kwizera', 'Enumerator'],
    ['claudette.igiraneza', 'Transcriber'],
    ['theophile.kalisa', 'Enumerator'],
    ['silas.gasasira', 'Enumerator'],
    ['josiane.uwamahoro', 'Enumerator'],
    ['laetitia.uwera', 'Field Coordinator'],
    ['marie.rosemuhoza', 'Enumerator'],
    ['aulique.bereniceiguhozesindikubwabo', 'Enumerator'],
    ['christian.ndaruhuye', 'Enumerator'],
    ['elithe.redemptainara', 'Enumerator'],
    ['obed.nahayo', 'Field Supervisor'],
    ['blandine.uwera', 'Enumerator'],
    ['eric.ntaganira', 'Enumerator'],
    ['alain.christianruzindana', 'Enumerator'],
    ['albert.dukuzumuremyi', 'Enumerator'],
    ['alain.mwizerwa', 'Enumerator'],
    ['ross.erickarambizi', 'Enumerator'],
    ['emerance.iragena', 'Enumerator'],
    ['malik.martialmanziruzindaza', 'Enumerator'],
    ['odette.nishimwe', 'Enumerator'],
    ['didier.gashema', 'Enumerator'],
    ['aline.uwineza', 'Enumerator'],
    ['ange.sybillesingiza', 'Enumerator'],
    ['norette.ingabire', 'Translator'],
    ['pamela.rudahunga', 'Transcriber'],
    ['pamela.marieclaudemizero', 'Enumerator'],
    ['gaudence.ndayambaje', 'Enumerator'],
    ['marie.nellyadelineuwayezu', 'Field Supervisor'],
    ['alice.mukeshimana', 'Enumerator'],
    ['erick.joseph', 'Enumerator'],
  ];

  static const List<String> countries = [
    '                                Country',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia & Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Myanmar/Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Great Britain',
  'Greece',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel and the Occupied Territories',
  'Italy',
  'Ivory Coast (Cote d\'Ivoire)',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyz Republic (Kyrgyzstan)',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Republic of Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Korea, Democratic Republic of (North Korea)',
  'Norway',
  'Oman',
  'Pacific Islands',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent\'s & Grenadines',
  'Samoa',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovak Republic (Slovakia)',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Korea, Republic of (South Korea)',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor Leste',
  'Togo',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks & Caicos Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United States of America (USA)',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (UK)',
  'Virgin Islands (US)',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  ];
}

